### ISSUE TITLE
Stream Failed to Load on Samsung TV (Tizen 8)

### ISSUE THREAD

**Issue by bigdaddyojan** [Stremio/stremio-bugs#1342]
### Stremio Platform

Samsung Native TV

### Describe the bug

As title says, on the last 3 days, I cant load anything on Stremio. I’m using S90D Samsung TV running on Tizen OS using Stremio App from their Appstore. 

I tried:
1. Reinstall app
2. Cold restart
3. Clear cache
4. Login on stremio website (cant stream)
5. Click reload on server status

I read some user have similiar trouble as I do but seems like no solution as per now. What should I troubleshoot this issue?

### To Reproduce

I tried:
1. Reinstall app
2. Cold restart
3. Clear cache
4. Login on stremio website (cant stream)
5. Click reload on server status

### Expected behavior

I read people troubleshoots as list above works but none for me

### TV (if applicable)

Device: Samsung S90D
OS: Tizen 8

### Logs

```shell

```

**Comment by TRtomasz** [comment]
Whats server status is it online? If you go to the settings -> about does it say web or tizen os?

**Comment by bombadillo** [comment]
I'm having the same issue. It was working fine until yesterday. 

Version: Theatre v1.7.2
Platform: Tizen 8

Server shows as offline. When I try the reload option "vnull" appears underneath "offline".

**Comment by jaruba** [comment]
normally fixed by unplugging your tv from the power socket for 10s, i opened the samsung tv app today and the server was showing as online (2019 samsung tv) so it is not a general issue

**Comment by bombadillo** [comment]
> normally fixed by unplugging your tv from the power socket for 10s, i opened the samsung tv app today and the server was showing as online (2019 samsung tv) so it is not a general issue

I tried that but the issue persists. I also tried clearing cache and data via Samsung settings and logging in and out of the account.

**Comment by jaruba** [comment]
not sure what to suggest in that case, very few people mentioned that unplugging the tv from the power socket stopped solving this issue for them, and only recently

**Comment by mattietea** [comment]
I seem to be having a similar issue with my Samsung TV - I can log into my account but addons don't sync. 

Version - Theaterv1.7.2
Platform - Tizen5.5
Server (online) - v4.20.8

**Comment by mendesanna** [comment]
I'm currently also having this problem 'Your device does not support the stream' on my Samsung tv. I already cleared the cash, reinstalled the app, unplugged the tv for 10 seconds and nothing
Version - Theaterv1.7.2
Platform - Tizen8
Server says offline and does not allow to reload

Is anyone looking into this?

**Comment by thanveeralisayed** [comment]
My Samsung TV, bought last year, has similar problems. The app isn't stuck, but playback causes the TV to hang. Occasionally, the video plays without subtitles, and the remote stops responding. To resolve this, I must force restart the TV by holding the power button on the remote. The issue started yesterday. I have even reset my tv.

**Comment by thanveeralisayed** [comment]
It looks like my issue was little different. I had some speed problems yesterday with real debrid. So I switched from Mumbai(automatic )server to cloudflare . I started getting full speed. Then I forgot about that. Since then the issue started with my samsung TV.  It looks like there is seeking issue when cloudflare server is set (reported by some others users as well in the reddit. Not just in tizen platform but in other platforms as well). So  I switched the real debrid cdn server back to automatic. Now everything works fine for me.

**Comment by rr-OAS** [comment]
Was working fine until today. "Stream failed to load" appears on all titles

Version: Theater v1.7.6
Platform: Tizen 8
Server: v4.20.8

Rebooted, cold Rebooted, reinstalled, cleared cache & data. No joy.

**Comment by natanaelAguiar** [comment]
Same issue here. It stopped to work suddenly with an error “Stream failed to load”

Version: V1.7.6
Platform: Tizen 6.5
Server: 4.20.8 and it is online

**Comment by yagorundy** [comment]
Same issue as well, streams are not loading with error "Stream failed to load"

Version: V1.7.6
Platform: Tizen 8
Server: v4.20.8

For me it got fixed by going to Settings -> Server -> Reload and then immediately going to the movie and playing it

**Comment by bhardwaj-abhi** [comment]
Threater v1.8.1 / Tizen 8 / Server is online.
Getting "Stream failed to load" error on Samsung Smart TV(2025 version)

Noticed -  It works sometimes when using without RD. Stream buffer a lot but starts alreast, sometimes.
With RD, it does not work at all. Getting this error every single time on Samsung TV.

**Comment by jaruba** [comment]
change dns provider on ur tv to google or cloudflare dns, u can google on how to do it, ur tv or ur isp is blocking domains

**Comment by andygm** [comment]
> change dns provider on ur tv to google or cloudflare dns, u can google on how to do it, ur tv or ur isp is blocking domains

Same problem, installed yesterday and don’t works. Today in the morning works, but suddenly stops after 6 hours.
The only problem is with the TV (Tizen 6.5), I have a Samsung projector (Tizen 8) and works well, as all the other devices.

Cold start, app reinstall, server reload and dns change don’t fix the problem.
Codec support isn’t because it works for some time. 
The TV don’t receives any new software updates in this days.

**Comment by flashfs** [comment]
Incredible. I've watched just yesterday and then today the same episode just shows "your device does not support the stream".

**Comment by N0edL** [comment]
I'am having the same issue on my new samsung tv

- Version: Theater v1.8.3
- Platform: Tizen 6

**Comment by LeGeRyChEeSe** [comment]
Hello, i was using Torrentio without any issue until now, so i switched to AIOStreams with some addons like Comet, Meteor, Library, MediaFusion, etc. And i'm getting now the same issue as you while it works on my Android Stremio App and web stremio. Maybe i suspect the server that host aiostreams doesn't handles well encoding thing relating with the streaming files.

**Comment by rishabdutta** [comment]
I am pretty sure Tizen has issue with AIOStreams. I recently made the move of using AIOStream. It worked perfectly on my phone, PC, macbook but won't work on my Samsung TV. So I switched back to TorrentIO and it started working again.

**Comment by dindu-nuffin69** [comment]
> I am pretty sure Tizen has issue with AIOStreams. I recently made the move of using AIOStream. It worked perfectly on my phone, PC, macbook but won't work on my Samsung TV. So I switched back to TorrentIO and it started working again.

it's not for me as none of my addons work.

> change dns provider on ur tv to google or cloudflare dns, u can google on how to do it, ur tv or ur isp is blocking domains

I'm using Cloudflare/Quad9 DNS, and still have the issue.
