### ISSUE TITLE
Stremio for IOS - Trakt Scrobbling Not Working Properly

### ISSUE THREAD

**Issue by Korngsok** [Stremio/stremio-bugs#1388]
### Stremio Platform

iOS / iPadOS / macOS Native Beta

### Describe the bug

On Stremio for IOS beta from Testflight, the trakt scrobbling feature doesn't seem to work properly. Therefore, content is not being marked as watched on Trakt.
To get it to work temporarily, I need to go to Stremio Web and log out and authenticate trakt again for this to work. However, it will stop working after some time.

### To Reproduce

Download Stremio for IOS from Testflight

### Expected behavior

Content being marked as watched on Trakt

### Logs

```shell

```

**Comment by AlvinHV** [comment]
@Korngsok I assume this is what you experiencing right? 
https://github.com/Stremio/stremio-bugs/issues/1389

**Comment by Korngsok** [comment]
> [@Korngsok](https://github.com/Korngsok) I assume this is what you experiencing right? [#1389](https://github.com/Stremio/stremio-bugs/issues/1389)

Yes, I reported in Reddit and was asked to create an issue in Github.

**Comment by Korngsok** [comment]
Hello, can I follow up if there will be a fix soon, pls?

**Comment by kvenn** [comment]
I'm also experiencing this

**Comment by bully-ur-dad** [comment]
I have this same issue but for stremio as a whole. iOS, android, and androidtv. None of them scrobble properly. Seems to be a common issue from what I can see on forums.

**Comment by AlvinHV** [comment]
I cannot finish implementation in iOS without trakt issue on fixed in backend

**Comment by wizaarddlabs** [comment]
+1

**Comment by AlvinHV** [comment]
Should be fixed in 1.3.3b1. Please confirm with testflight if it works

**Comment by Korngsok** [comment]
> Should be fixed in 1.3.3b1. Please confirm with testflight if it works

Just updated, still not working for me. 
I also tried logging out and in but still not working.
