### ISSUE TITLE
Trakt Reauthentication Error

### ISSUE THREAD

**Issue by rjr4m** [Stremio/stremio-bugs#1436]
### Stremio Platform

Desktop (macOS)

### Describe the bug

Stremio keeps giving me an error message saying Trakt authentication keeps expiring and tells me to re-authenticate. This somehow leads to scrobbling features not working on my Firestick (Android TV) as well; I watched a movie today and it didn't seem to log the movie in my Trakt history.

### To Reproduce

It seems to happen every time I open up Stremio every few days on my macbook.

### Expected behavior

No error message whatsoever and Trakt stays authenticated on my account.

### Screenshots

<img width="626" alt="Image" src="https://github.com/user-attachments/assets/830e0ea9-dbf5-4ce9-8825-d5bcbd42fdfc" />

### Desktop (if applicable)

OS: Mac
Version: 4.4.168

### TV (if applicable)

Device: Fire TV Stick 4K Max (2nd Gen)
OS: Fire OS
Software Version: 8.1.3.6 (RS8136/3332)
Home Version: 6580006.1

### Logs

```shell

```

### Notes

When I reauthenticate, it also keeps re-adding the Trakt Integration add-on, which I don't want because it keeps cluttering up my home page and my library when added. Is there a way to not only keep the authentication from expiring so often, but also either configure what the Trakt integration adds to my stremio client or just stop the automatic adding in general?

**Comment by dexter21767-dev** [comment]
Hey @rjr4m, next time u see that popup close the app and reopen it and tell me if it appears again after u reopen.

**Comment by unleashed7** [comment]
@Practicalbutterfly5 It is the same cause, as the issue is on Stremio's side!

**Comment by premiumcreativeuser** [comment]
I'm experiencing the same issue—Trakt scrobbling through Stremio only stays authenticated for a few hours before it stops working. I end up having to re-authenticate repeatedly, which doesn’t seem normal.

My setup includes three Firesticks running Stremio with Trakt scrobbling enabled.

Re-authenticating via [Stremio account settings](https://www.stremio.com/acc-settings) doesn’t resolve the issue unless I first revoke access through [Trakt’s authorized applications page](https://trakt.tv/oauth/authorized_applications) and then go through the entire setup process again.

Anyone know of a better way to make the Stremio Trakt scrobbling authentication last longer than a few hours? 

Unfortunately re-authenticate through one of the 3 routes below isn't so simple. I also receieved the following message "Application revoked." after authenticating and going back to trakt.tv My trakt account has stopped scrobbling and doesn't how any history for the past 48 hours. 

1. Route 1 - https://www.stremio.com/acc-settings - Will have you login https://api.trakt.tv/auth/signin and once authenticated it shows connected apps to your trakt account. This route does not add the Trakt Integration v.1.0.0 addon to Stremio.
2. Route 2 - https://web.stremio.com/#/settings - Will have you login https://api.trakt.tv/auth/signin and once authenticated it shows connected apps to. your trak account. This route will add the Trakt Integration v.1.0.0 addon to Stremio.
3. Route 3 - Using the Stremio app. I'm on macos and tested on 4.4.168. Went to Settings > General > Trakt Scrobbling > Authenticate. This also adds the Trakt Integration v.1.0.0 addon to Stremio.

PS. I also tried force stopping Stremio, clearing the cache, going to stremio > addons then sync addons, and restarting the device multiple times but still not seeing the scrobbling being active on trakt.tv. 

After serveral attemps I finally got the red ribbon with the message "You are watching" on trakt.tv. I had to authenticate from multiple routes in order for it to start working. But the bigger issue is for it to last more than 24 hours... I'm using this app daily and watching multiple titles and episodes per day. Not seeing it saved on my history. 

As an additional test I also tried deleting the Trakt Integration v.1.0.0 addon on Stremio, then sync addons to remove the additional playlist and the Trakt Scrobbling still works. But no more than 24 hours before it breaks then you have to repeat all this again. It makes no different keeping or deleting the Trakt Integration v.1.0.0 addon. 

![Image](https://github.com/user-attachments/assets/b49be68b-dcb0-408f-bb98-16b3fa36560a)

![Image](https://github.com/user-attachments/assets/5769b4d9-f373-462d-be3b-1e0993f7f448)

**Comment by unleashed7** [comment]
@premiumcreativeuser Sadly we cannot refresh the token ourselves, only they can as we don't have their key to refresh/generate new OAuth tokens. But I solved it with a simple puppeteer setup here: https://github.com/Stremio/stremio-bugs/issues/1427#issuecomment-2907532968

It's odd that it doesn't let you authenticate sometimes, for me when I have the orange message, I get the Authenticate button in the account settings and can do it as usual, never had to remove from Trakt first.

**Comment by premiumcreativeuser** [comment]
> [@premiumcreativeuser](https://github.com/premiumcreativeuser) Sadly we cannot refresh the token ourselves, only they can as we don't have their key to refresh/generate new OAuth tokens. But I solved it with a simple puppeteer setup here: [#1427 (comment)](https://github.com/Stremio/stremio-bugs/issues/1427#issuecomment-2907532968)
> 
> It's odd that it doesn't let you authenticate sometimes, for me when I have the orange message, I get the Authenticate button in the account settings and can do it as usual, never had to remove from Trakt first.

Unfortunately I don't get a notification that the token has expired unless I login to https://www.stremio.com/. Even when trying to authenticate again via https://www.stremio.com/ and completing the login steps through https://api.trakt.tv/auth/signin then checking https://trakt.tv/oauth/authorized_applications I notice that the existing connected apps don't technically refresh and it still shows the date of the first time I authenticated. I have to delete everything and start over to get it working again. 

I'd like to try your method but don't have the experience using node or puppeteer or knowing where or how to run what you are proposing. I nee a step by step instructions for setting that up.

**Comment by premiumcreativeuser** [comment]
> [@premiumcreativeuser](https://github.com/premiumcreativeuser) Sadly we cannot refresh the token ourselves, only they can as we don't have their key to refresh/generate new OAuth tokens. But I solved it with a simple puppeteer setup here: [#1427 (comment)](https://github.com/Stremio/stremio-bugs/issues/1427#issuecomment-2907532968)
> 
> It's odd that it doesn't let you authenticate sometimes, for me when I have the orange message, I get the Authenticate button in the account settings and can do it as usual, never had to remove from Trakt first.

Also, what exactly does this script do? If you were to run it on one device would it also affect all the other devices you run the application on or only that one device you are running the script on? 

I tried creating an action workflow on github but stuck with the following:

*UPDATE* I adjusted the login credentials for Stremio rather than Trakt and that seemed to succesfully run the action. I saw the message Auth button not found on Stremio: Probably still authenticated. But I'm still unclear how this works an if it will work across all my firestick devices. 

![Image](https://github.com/user-attachments/assets/991a205e-f759-4581-b3fe-8e68e4b15a2d)

![Image](https://github.com/user-attachments/assets/fac79d73-4d9b-4e2c-a2f6-2282d2ed0080)

**Comment by premiumcreativeuser** [comment]
One other thing I noticed while setting up Trakt Scrobbling is that the login doesn't seem to carry over to the Stremio app on macOS. When I authenticate via the browser, it shows that I'm logged into Trakt Scrobbling there, but the Stremio app itself still requires me to log in separately. Is this expected behavior? Shouldn't the app automatically recognize that I'm already authenticated through the browser? Screenshot below showing this behavior.

![Image](https://github.com/user-attachments/assets/4f8792a5-24b2-472e-aa3b-a217efc3a1c5)

**Comment by TRtomasz** [comment]
You would have to relogin in mac os app for this to be detected

**Comment by premiumcreativeuser** [comment]
> You would have to relogin in mac os app for this to be detected

I think it eventually auto logged itself into trakt. Unless I went in auto pilot mode and manually logged in but I'm now seeing it logged in on the Stremio app. I don't think I manually went in an logged in again. Maybe it took some time to auto update?

**Comment by unleashed7** [comment]
@premiumcreativeuser Sometimes it takes a few seconds for this to be reflected, but it shouldn't take long. Force closing the app and reloading might help it refresh. On Windows it's refreshed real-time when you click inside the app, might not work like that there.

If you see "Auth button not found" then most likely you're okay, like I said in the other post it's easy to test it. Just keep logging out, running the script and refreshing the stremio account setting page to see how it behaves and if it works everytime or not.

**Comment by DanaramaPyjama** [comment]
This has been happening to me for quite some time.  I don't always get the pop up, because I'll be watching on my Android TV.  I'll notice something hasn't scrobbled on Trakt, go to settings on my Android mobile client, and see I've been logged out.

**Comment by unleashed7** [comment]
@DanaramaPyjama Yeah, it's a confirmed issue at this point. You can try to use this as a workaround: [https://github.com/Stremio/stremio-bugs/issues/1427#issuecomment-2907532968](https://github.com/Stremio/stremio-bugs/issues/1427#issuecomment-2907532968)

**Comment by DanaramaPyjama** [comment]
> [@DanaramaPyjama](https://github.com/DanaramaPyjama) Yeah, it's a confirmed issue at this point. You can try to use this as a workaround: [#1427 (comment)](https://github.com/Stremio/stremio-bugs/issues/1427#issuecomment-2907532968)

Thank you. May use it.  I've already got a python that refreshes my auth for Trakt, so i may look at extending that, using this for inspiration.

orrr, I may just wait.  Haven't decided.  but thank you none-the-less

**Comment by kWazt** [comment]
> > [@DanaramaPyjama](https://github.com/DanaramaPyjama) Yeah, it's a confirmed issue at this point. You can try to use this as a workaround: [#1427 (comment)](https://github.com/Stremio/stremio-bugs/issues/1427#issuecomment-2907532968)
> 
> Thank you. May use it.  I've already got a python that refreshes my auth for Trakt, so i may look at extending that, using this for inspiration.
> 
> orrr, I may just wait.  Haven't decided.  but thank you none-the-less
> 

I issue affects me too, without fail. Every time I open the app on Android. Python sounds good, would you mind sharing?

**Comment by DanaramaPyjama** [comment]
> > > [@DanaramaPyjama](https://github.com/DanaramaPyjama) Yeah, it's a confirmed issue at this point. You can try to use this as a workaround: [#1427 (comment)](https://github.com/Stremio/stremio-bugs/issues/1427#issuecomment-2907532968)
> > 
> > 
> > Thank you. May use it.  I've already got a python that refreshes my auth for Trakt, so i may look at extending that, using this for inspiration.
> > orrr, I may just wait.  Haven't decided.  but thank you none-the-less
> 
> I issue affects me too, without fail. Every time I open the app on Android. Python sounds good, would you mind sharing?

I don't have a full script for this.

I've just had to redo my trakt auth from my old script as it had missing data.

This python script checks for toek in json format.  If exists, prints username.  If not exist, you have to copy the code it gives you into a browser.

https://github.com/DanaramaPyjama/trakt/blob/main/trakt_auth.py

I've tested expiration and it works as I would expect.  It just gets a new token.

**Comment by unleashed7** [comment]
> https://github.com/DanaramaPyjama/trakt/blob/main/trakt_auth.py
> 
> I've tested expiration and it works as I would expect. It just gets a new token.

Thanks for sharing this! Looks like a more elegant solution to the problem, I might implement it myself when got the time.

**Comment by DanaramaPyjama** [comment]
> > https://github.com/DanaramaPyjama/trakt/blob/main/trakt_auth.py
> > I've tested expiration and it works as I would expect. It just gets a new token.
> 
> Thanks for sharing this! Looks like a more elegant solution to the problem, I might implement it myself when got the time.

You're welcome.  It's missing some basic functions like having to work with hard coded valaues (particularly for path) and there's no encryption used either.

It's particularly annoying because I thought I had all this, then I checked my old scripts and somehow I'd lost part of it :(

Oh well we have it now and I can get on wit the project I was supposed to be working on. :D

**Comment by rjr4m** [comment]
Anyone else feel like it's getting worse? Now it seems like a trakt authentication token only lasts for a couple hours at most. I've had to re-authenticate like 3 times today because Stremio wasn't scrobbling a show I was watching to Trakt.

**Comment by unleashed7** [comment]
@rjr4m Based on the logs from the auto-login script I use, it's still the same, expires every 24 hours.

**Comment by DanaramaPyjama** [comment]
@rjr4m @unleashed7 

Yeah it is getting worse for me.  The token does still expire every 24 hours.  Stremio actually implemenetd refresh_token back in Feb 2024 I think it was, so it should be working and for me sometimes it is!

I didn't even used to have this issue when Trakt moved the expiration period to 24 hours.  It took a month before I started getting issues.  And the refresh-token is working sometimes, because my issue can still disappear for a week or so then come back.  These last 7 days though, it actually has been every day without fail so the frequency for me is definitely worse of late.

Actually, I think last 2 days I've remained logged in, but the 5 days prior I had to re-auth every day.

**Comment by unleashed7** [comment]
@DanaramaPyjama That is an interesting observation. Honestly, I cannot pinpoint when this started happening, as I only learned about the Trakt change in March recently, but I do think I had this problem since then. And right now, for me it never works, without exception it expires at the 24h mark and my script logs me in at the next scheduled time.

Now I wonder if it's a bug in Stremio's implementation to refresh tokens, if there's one present after all.

**Comment by DanaramaPyjama** [comment]
> [@DanaramaPyjama](https://github.com/DanaramaPyjama) That is an interesting observation. Honestly, I cannot pinpoint when this started happening, as I only learned about the Trakt change in March recently, but I do think I had this problem since then. And right now, for me it never works, without exception it expires at the 24h mark and my script logs me in at the next scheduled time.
> 
> Now I wonder if it's a bug in Stremio's implementation to refresh tokens, if there's one present after all.

I think it's either a bug in the refresh code, or potentially under-resourced infrastructure.  I know there had been problems with inconsistent scrobbling in the past, even before this issue was raised that was due resource.  Capacity management could also explain why it either;

1) Happens every day for someone
2) Happens sometimes for someone else
3) Doesnt affect someone at all.

Capacity / resourcing makes more sense to me than code.

**Comment by dexter21767-dev** [comment]
This issue should be fixed now. can you guys test it for the next few days and report back? 
please test without using external tools so we can get accurate results.

**Comment by rjr4m** [comment]
> This issue should be fixed now. can you guys test it for the next few days and report back? please test without using external tools so we can get accurate results.

Will do. So far so good, as of today! 👍🏼 Will keep you posted.

**Comment by unleashed7** [comment]
@dexter21767-dev As mentioned in the other issue, still logged in after 2 days. I'll keep the checker running for a week and see, but it does seem to be resolved!

Thanks again for the fix!

**Comment by bully-ur-dad** [comment]
@dexter21767-dev the issue is still happening.  I've had to reauth all my accounts again this morning. Users on reddit are also still reporting the issue. 

Edit: Again just now, I had to reauthenticate mine and my families accounts.

**Comment by Tutere** [comment]
Yeah I've noticed that it doesn't necessarily ask me to reauth now, but will just stop tracking/scrobbling in the background. I left it for a couple days and looks like it hasn't picked up what I've been watching

**Comment by bully-ur-dad** [comment]
> Yeah I've noticed that it doesn't necessarily ask me to reauth now, but will just stop tracking/scribbling in the background. I left it for a couple days and looks like it hasn't picked up what I've been watching

Not sure if it shows in the app as I always long in through the website to check. Sure enough, today I had to reauthenticate everything again.

**Comment by rjr4m** [comment]
> This issue should be fixed now. can you guys test it for the next few days and report back? please test without using external tools so we can get accurate results.

Weirdly enough, opposed to everyone else, things are still working well for me. Stremio's been tracking my watch history onto Trakt and I haven't needed to reauthenticate once 🤷🏻‍♂️

**Comment by bully-ur-dad** [comment]
> > This issue should be fixed now. can you guys test it for the next few days and report back? please test without using external tools so we can get accurate results.
> 
> Weirdly enough, opposed to everyone else, things are still working well for me. Stremio's been tracking my watch history onto Trakt and I haven't needed to reauthenticate once 🤷🏻‍♂️

That's awesome. I've noticed some accounts will last slightly longer before they need to reauthenticate, but over the 5 accounts that I do it for, within 48 hours all of then need to be reauthenticated everytime =/

**Comment by rjr4m** [comment]
> Yeah I've noticed that it doesn't necessarily ask me to reauth now, but will just stop tracking/scrobbling in the background. I left it for a couple days and looks like it hasn't picked up what I've been watching

Alright, this is starting to happen to me now too: no notification to reauthenticate but hasn't been logging what I've been watching onto Trakt.

Edit: Literally as I was typing this out, a notification to reauthenticate finally pops up :/

**Comment by Djlilyazii** [comment]
After every few days @dexter21767-dev 



<img width="1125" height="2436" alt="Image" src="https://github.com/user-attachments/assets/b740e3c9-0759-4b7c-87cd-f9235b27d6d8" />

**Comment by unleashed7** [comment]
@dexter21767-dev It is true unfortunately, since 2nd of July the issue returned. I kept my solution running and between 6/19 and 7/2 wasn't logged out even once! So it was clearly working, but the past few days, it has to auth my accounts again every 24 hours.

One weird thing is, only 3 of my 4 accounts expire daily my main one expired on 2nd and 3rd, but now it's logged in for 3 days straight. Couldn't explain that even if I tried.

**Comment by bully-ur-dad** [comment]
> [@dexter21767-dev](https://github.com/dexter21767-dev) It is true unfortunately, since 2nd of July the issue returned. I kept my solution running and between 6/19 and 7/2 wasn't logged out even once! So it was clearly working, but the past few days, it has to auth my accounts again every 24 hours.
> 
> One weird thing is, only 3 of my 4 accounts expire daily my main one expired on 2nd and 3rd, but now it's logged in for 3 days straight. Couldn't explain that even if I tried.

It never worked for me on any of the accounts I manage for my family.  Glad it worked for some temporarily, but the issue was never fixed on a large scale.

**Comment by HDZ-Rakun** [comment]
still have the issue. 

when checking the Trakt Connected Apps, all other Trakt-related Addons get refreshed normally (Up-Next-Stremio, Trakt for iOS and Stremio Trakt Addon v1 by dexter) - a new date appears every day under "Connected on" for every one of them.

The Stremio integration addon however just doesn't update, it works for one day after you redo it from scratch, and then it never refreshes again, and the "Connected on" date stays the initial date of connection and never updates.

**Comment by bully-ur-dad** [comment]
Yea it's not even keeping them authenticated for a full 24 hours anymore for me =/ 

Edit: it also appears that it is no longer scrobbling most of the stuff I watched even while it is currently authenticated...

**Comment by WagurinPudding** [comment]
It's so annoying, ngl.

**Comment by mindstop** [comment]
the issue is still occurring.. hope the devs pick it up soon!

**Comment by TRtomasz** [comment]
@mindstop and everyone else if you think that your are affected by this issue please provide details like
1. App you are using and app version also os 
2. In what way the issue appears - do you see any error message or something else?
3. If possible provide screenshot/video

**Comment by WagurinPudding** [comment]
@TRtomasz It occurs on Stremio for Android. Using 1.6.13 which I believe to be the latest stable verison. I'm currently on AOSP Android 15 and the issue persists regardless of my ProtonVPNplus connection. Usually, whenever I re-open stremio every 1.5-2 days, the popup  saying auth expired and to re-authenticate shows up right when it's loading my trakt continue watching, catalogues and other extensions. Sometimes, when I go to Settings tab to re-authenticate, it automatically shows logged in, but most of the times it doesn't and I have to re-authenticate. I believe this has something to do with the connection between trakt-next extension itself with the scrobbler auth of the app. It's just conflicting I open the application every 36 hours or so.

<img width="1080" height="2400" alt="Image" src="https://github.com/user-attachments/assets/4828ca96-b017-4a51-ab8a-9f8762c8f576" />

**Comment by TRtomasz** [comment]
@pawankushum  thanks, any chance you can sign up to the beta version from playe store?

**Comment by mindstop** [comment]
@TRtomasz is there any other way to download beta version? Stremio is not available in my country's play store.

**Comment by TRtomasz** [comment]
@mindstop  not right now, will think about some way to make it available

**Comment by HDZ-Rakun** [comment]
So it just started working randomly now after being broken for 2 weeks. I didn't do anything on my side as I kinda gave up due to it only working for less 24h, but the Trakt Connected Apps now has today's date for Stremio, on its own.

But to provide details... I use Stremio App for LG TV (WebOS), latest version... and Stremio 5 Beta on Windows 11 and the Web version, but I only use these for setup and not really for watching.

EDIT: I also point out again that Up-Next-Stremio, Trakt for iOS and Stremio Trakt Addon v1 by dexter (so, not the official integration but the one for lists etc) all work fine and refresh daily on their own.

**Comment by bully-ur-dad** [comment]
![Image](https://github.com/user-attachments/assets/7810042b-79ca-4f46-b8fb-eca29849318c)
I am using the most up-to-date android beta and a galaxy s23u thats fully updated. But its also happening on other accounts I manage for family using windows, android tv, and iOS (both tablet and phone).  I have tried reauthenticating through the beta app, stremio web app, and stremio website.  I've gone to just checking the stremio website everyday to reauthenticate all as it is the fastest method for me, and if I don't nothing gets scribbled on my trakt history.  Actually, I've noticed that even while authenticated, I'm getting gaps in watched history.  Movies almost never scrobble.

**Comment by Tutere** [comment]
I use a Nvidia shield, so just watch via the stremio for android tv (through google play store). I only use the mac os dektop app for setup or if I notice a problem with one of my addons - since it cant be reconfigured via the tv app. While using the TV version of the app I typically dont get an error message, I just notice that it stops scrobbling in the background once I go back to Trakt after a couple days to review my history.

When that happens, I'll quickly log in to the web version via my ipad (for convenience),logout then re-authenticate. That usually carries over to my TV version once I restart the app.

The last day or so I've had new api fetching errors pop up on my TV app - when that happens, I cant load movies/shows so have to do a restart. Not sure if that is related so haven't included screenshots for the time being. Will come back to this thread and post again if I notice it being somehow connected to the trakt authentication.

**Comment by TRtomasz** [comment]
Tried current Android TV app and non beta mobile app, both apps triggers action to refresh trakt token(when app is used)
To ensure you have token refreshed you should force close the app and reopen it again
In very rare cases, It could happen that refresh will fail but we have no warning about this, you will see a regular warning about expired token next time you open the app

**Comment by mindstop** [comment]
@TRtomasz are saying the issue is fixed in both Android tv app and non beta android mobile app?

**Comment by HDZ-Rakun** [comment]
It's most definitely not fixed. After working for a week or 2, no scrobbling again today, but also no message about expired authentication.

**Comment by TRtomasz** [comment]
No scrobbling is not related to authentication issue so please do not mix these two @HDZ-Rakun

**Comment by DanaramaPyjama** [comment]
> No scrobbling is not related to authentication issue so please do not mix these two [@HDZ-Rakun](https://github.com/HDZ-Rakun)

Scrobbling no longer working is a symptom of being logged out. 

What do you mean, they're unrelated?

**Comment by bully-ur-dad** [comment]
Its definitely not fixed. I have had to reauthenticate multiple accounts in the last 15 hours

**Comment by TRtomasz** [comment]
> > No scrobbling is not related to authentication issue so please do not mix these two [@HDZ-Rakun](https://github.com/HDZ-Rakun)
> 
> Scrobbling no longer working is a symptom of being logged out.
> 
> What do you mean, they're unrelated?

issue is about having to reauthenticate every 24 hours not about scrobbling not working

**Comment by DanaramaPyjama** [comment]
> > > No scrobbling is not related to authentication issue so please do not mix these two [@HDZ-Rakun](https://github.com/HDZ-Rakun)
> > 
> > 
> > Scrobbling no longer working is a symptom of being logged out.
> > What do you mean, they're unrelated?
> 
> issue is about having to reauthenticate every 24 hours not about scrobbling not working

So don't mention symptoms, in case dev confused?  

FYI, though I'm pretty sure you're already aware sinceyou've been following this from the beginning.... We don't always get an authentication error.  We sometimes only notice that scrobbling has stopped working, using manual checks.  We then use that knowledge to check the stremio settings and then find out that failed refresh_token has caused forced log out.

Luckily some of us are using a workaround and no longer have this issue.

Edit > Reading this sounds rude.  I apologise, that is not my intention.  That said, I don't know how to reword it to not sound rude either.

**Comment by DanaramaPyjama** [comment]
> Its definitely not fixed. I have had to reauthenticate multiple accounts in the last 15 hours

If you're technical enough, a user did implement a node.js and pupeteer workaround that you can find if you search these issues closely enough.

It works great.

**Comment by TRtomasz** [comment]
> So don't mention symptoms, in case dev confused?

Sure scrobbling will not work in case you are not logged in trakt but this is not the same issue. As trakt scrobbling can not work due to multiple issues not only when user is not authorized so mixing these two do not help with solving the issue at hand.
We have a system that will refresh user token before trying to send anything to trakt so this is one of the actions that triggers token refresh.
Token will be also refreshed when you close and reopen app, log in again to the app and during some navigation actions - depending on the app, different actions make this happen. 
Two apps do not have any notification about trakt - New mobile app(in beta) and tv apps
I would not consider reopening user profile (at stremio.com) as a source of truth especially on mobile phone as mobile browser use heavy caching and selecting it from already open tabs could not trigger trakt token refresh. Refresh the webpage if you see the notification it should be gone and your token should be refreshed, same goes for other apps that show notifications, just reopen the app or refresh it with f5

**Comment by bully-ur-dad** [comment]
> > Its definitely not fixed. I have had to reauthenticate multiple accounts in the last 15 hours
> 
> If you're technical enough, a user did implement a node.js and pupeteer workaround that you can find if you search these issues closely enough.
> 
> It works great.



> > So don't mention symptoms, in case dev confused?
> 
> Sure scrobbling will not work in case you are not logged in trakt but this is not the same issue. As trakt scrobbling can not work due to multiple issues not only when user is not authorized so mixing these two do not help with solving the issue at hand. We have a system that will refresh user token before trying to send anything to trakt so this is one of the actions that triggers token refresh. Token will be also refreshed when you close and reopen app, log in again to the app and during some navigation actions - depending on the app, different actions make this happen. Two apps do not have any notification about trakt - New mobile app(in beta) and tv apps I would not consider reopening user profile (at stremio.com) as a source of truth especially on mobile phone as mobile browser use heavy caching and selecting it from already open tabs could not trigger trakt token refresh. Refresh the webpage if you see the notification it should be gone and your token should be refreshed, same goes for other apps that show notifications, just reopen the app or refresh it with f5

Thankfully I always refresh them in incognito because otherwise it tries to attach the previous trakt account so that portion wouldnt be the issue. Also done across multiple operating systems and apps.  out of 5 accounts I manage for family (send help) I'm still having to reauthenticate 2.  The 3 that have stayed just one at a time stayed authenticated, but it took several days refreshing each for me personally.

**Comment by unleashed7** [comment]
I gave up on this myself and just kept using my workaround for it which solves the issue. However, checking my logs now, it's still funny to see how sometimes their system seems to work, but mostly it doesn't.

For example between 7/22 and 8/1 (10 days) all 4 of my accounts remained fully authenticated, but since then it expires after 24 hours again, every single day. This happened without any usage, mind you, so it's definitely not because of their claimed systems in place which refreshes the token when interacting with the stremio app in different ways.

I cannot confirm, if their claim is true, I'm only stating that there is an underlying system that refreshes the token even when the account/app is not in use, but it's inconsistent to say the least.

**Comment by TRtomasz** [comment]
We had an issue between 01.08 and yesterday when by mistake previous service version has been deployed thats why you see this in the logs, it is fixed now.

**Comment by bully-ur-dad** [comment]
Issue still present. 3 out of 5 needed reauthenticating today.

**Comment by TRtomasz** [comment]
what is the app version/os you are using for this 3 out of 5?

**Comment by Tutere** [comment]
It actually does seem to be working for me now. The last couple days the re-auth process has automatically occurred and although scrobbling is considered seperate, that has been working too. Will continue to monitor over the next week or so. I only use the TV app on Nvidia shield (would only log into web version to manually reauth if scrobbling stopped) so can't speak for other app versions.

**Comment by bully-ur-dad** [comment]
> what is the app version/os you are using for this 3 out of 5?

They are using different OS's and are all on the most up to date stremio.  Android, androidtv, iOS, and Windows. I reauthenticated through incognito windows on Firefox as it keeps from attaching wrong trakt account.  Also noticed about a week ago that if I log into an account through chrome (non incognito) it would show as needing reauth on an account, but if i logged into that account at the same time via incognito browser it would still say authenticated.  This is unrelated to the accounts needing reauth, because weirdly, that account has stayed authenticated. But I figured it couldn't hurt to include. Also since it was mentioned above, scrobbling still not scrobbling movies for me.

**Comment by TRtomasz** [comment]
Did they try to simply restart their app? if they just leave apps open without doing anything there is a chance they will not trigger the reauth or if you check before they do anything reauth will also not be triggered but this is not a bug.

**Comment by bully-ur-dad** [comment]
> Did they try to simply restart their app? if they just leave apps open without doing anything there is a chance they will not trigger the reauth or if you check before they do anything reauth will also not be triggered but this is not a bug.

I restart the app daily, and I know the account I personally use and 1 other is used daily not sure about the others.  I know they all completely power down their computers/androidtv boxes before going to sleep each night if used.

**Comment by dexter21767-dev** [comment]
@bully-ur-dad how would u describe your internet? is it sometimes slow and laggy? 
also is the app showing some kind of popup telling u to reauth? or how are u keeping track of if you're logged in or not? 
are u noticing the issue happing on specific OSes / devices / trakt accounts?  
so far we are unsuccessful in reproducing this issue in any device no matter how we tried. any details will be appreciated.

**Comment by bully-ur-dad** [comment]
> [@bully-ur-dad](https://github.com/bully-ur-dad) how would u describe your internet? is it sometimes slow and laggy? also is the app showing some kind of popup telling u to reauth? or how are u keeping track of if you're logged in or not? are u noticing the issue happing on specific OSes / devices / trakt accounts? so far we are unsuccessful in reproducing this issue in any device no matter how we tried. any details will be appreciated.

My internet works pretty well. Usually 250mbps+ on the slow end unless there is an issue they have to come fix. There's 3 ways I usually notice it.  When it shows on settings on the stremio app that it doesn't have an account connected to scrobbling. when logging into a different account via the androidtv app, since it makes you use a QR code to sign in, which opens the stremio website for me to log into which then shows me that I need to reauthenticate.  I then check to confirm in incognito on firefox browser, because occasionally it will show that it needs reauth on Chrome but when I check on firefox it won't.  I also check via firefox incognito if I notice series (series scrobble perfect for me when scrobbling connected; only movies dont scrobble for me even when connected) in particular aren't scrobbling, and everytime this has said I need to reauthenticate.  I also try have been trying to check each one of these with another if that makes sense.  

If you need anything clarification on anything just let me know and i will try my best to clarify.  Currently sick as a dog so I might not be doing my best communicating lol

**Comment by dexter21767-dev** [comment]
@bully-ur-dad please message me on reddit or discord (dexter21767),
and i will do some checks for your accounts specifically, maybe we will be able to find some anomalities

**Comment by bully-ur-dad** [comment]
> [@bully-ur-dad](https://github.com/bully-ur-dad) please message me on reddit or discord (dexter21767), and i will do some checks for your accounts specifically, maybe we will be able to find some anomalities

Message sent

**Comment by Selym-git** [comment]
Same problem 😕

Version 1.6.13 arm64 (Android)

![Image](https://github.com/user-attachments/assets/06ae48ac-a72b-4d75-81d5-5b10f40e8821)

**Comment by TRtomasz** [comment]
as written before @Selym-git  have you tried to simply close and reopen the app?

**Comment by bully-ur-dad** [comment]
Issue still present for me as well.  Fully close app on daily bases.  Shows in app settings, stops scrobbling tv shows, and shows on the website.  Accounts stay authenticated longer at random, but always end up needing reauth within a week.

**Comment by Selym-git** [comment]
> as written before [@Selym-git](https://github.com/Selym-git) have you tried to simply close and reopen the app?

Yes, whenever I get this error, I need to close the app completely and open it again and it'll be fine until the next time. On my browser/windowsapp the error is in the corner and sometimes I dont notice it to do that, so trakt ends up not functioning. Its not a huge problem, just annoying.

**Comment by rs443** [comment]
I have this issue too, ~24 hours after setting up Trakt scrobbling. Sync is dead.

**Comment by rjr4m** [comment]
Been good on my side for a while. automatically scrobbling for the past couple weeks. Do we still have a lot of other people experiencing issues, though? Because if so, I'll keep the ticket up.

**Comment by bully-ur-dad** [comment]
Just had to reauth all accounts except 1, but tbf I hadn't checked them in a little over a week I think.  I'll report back in a few days.

**Comment by Tutere** [comment]
Mine was going good but after trying to setup aiostreams and messing with my addons (which I know shouldn't impact the main Stremio settings), the auth and scrobbling has been a bit patchy. The episode I was watching last night didn't get tracked, so will keep an eye on it over the next few days and report back.

**Comment by bully-ur-dad** [comment]
Had to reauthenticate 2 of the accounts today.  Slightly better but still not fixed for me.

**Comment by Tutere** [comment]
Seems to be working pretty well for me again now. Haven't had to re-auth since I last checked at start of the week and scrobbling working

**Comment by Tutere** [comment]
Damn it, spoke too soon lol. But to being unauthenticated today

**Comment by bully-ur-dad** [comment]
Had to reauth 3 accounts today, 1 of them being my personal account that is used daily.

**Comment by unleashed7** [comment]
Just reporting back after a month, based on my logs none of the 4 accounts (some active, some inactive) were unauthenticated the last 30 days! Thanks for fixing this 👍

**Comment by premiumcreativeuser** [comment]
> Just reporting back after a month, based on my logs none of the 4 accounts (some active, some inactive) were unauthenticated the last 30 days! Thanks for fixing this 👍

Let’s hope so. I had to stop using the login script you shared since I ran out of my free monthly GitHub Actions quota. The script has been inactive for the past four days. I’ll keep monitoring to see if my account remains authenticated without it.

**Comment by bully-ur-dad** [comment]
Just had to reauth 4 accounts. 2 of which I know are used regularly.

**Comment by premiumcreativeuser** [comment]
Did they make the authentication process automatic when logging into Stremio? I got a little worried because I left the Stremio web browser window open, and when I checked back, I noticed the 'Authenticate' button was active. I logged out and signed back in through stremio.com, and the button switched to 'Import/Log Out' without me manually clicking it. Gave me a bit of PTSD.

**Comment by bully-ur-dad** [comment]
Only had to reauth 2 tonight, and they were not as actively used accounts.

**Comment by bully-ur-dad** [comment]
> Only had to reauth 2 tonight, and they were not as actively used accounts.

Nevermind, the two that didn't need it ended up not scrobbling/needing to be reauthenticated as well as 2 others.

**Comment by rjr4m** [comment]
Stremio not tracking again. No error message this time but I just finished 2 movies at 2 different days this past week and Trakt didn't record either them, even after reauthenticating manually after the 1st movie.

**Comment by Djlilyazii** [comment]
my trakt account is authenticated the stremio android TV doesn't seem to scrobble anymore  Ita been 2 daya now with this issue

**Comment by Tutere** [comment]
> my trakt account is authenticated the stremio android TV doesn't seem to scrobble anymore  Ita been 2 daya now with this issue 

Yep me too. Was wondering if it's because I reordered my addons but should surely still work if I'm authenticated. Last couple days it seems to be broken

**Comment by premiumcreativeuser** [comment]
You're not alone, I only noticed yesterday that my accounts stopped tracking about two weeks ago. My personal Trakt history shows everything up until October 6, and the same issue happened across five friends and family's accounts I manage. I had to log back into Stremio and re-authenticate.

**Comment by Tutere** [comment]
Seems that it's back working again. At least the last couple days all my shows being tracked

**Comment by TRtomasz** [comment]
Closing this for now

**Comment by Djlilyazii** [comment]
Its not working again

**Comment by bartned** [comment]
I still have this bug
