### ISSUE TITLE
Library page does not show "Details" menu item

### ISSUE THREAD

**Issue by levynir** [Stremio/stremio-bugs#1510]
### Stremio Platform

LG Native TV

### Describe the bug

When selecting a multi-episode show from the Library view, the right side menu does not have a "details" menu item, and there is no way to get to the list of episodes.
I originally thought this is intentional and opened a feature request to add this, but from the answer in the original ticket I understand this may be a bug.

### To Reproduce

1. Install Stremio 1.6.0 on LG TV and sync plugins
2. Search for a show with multiple episodes (Sandman is one option)
3. Add to library
4. exit stremio
5. open stremio
6. go to library (remote control left, down, down, down, right)
7. click on the show
8. menu pops up from the right, menu have the following items: Play Now, Remove from Library, Mark as Unwatched, Trailer)

### Expected behavior

Menu should also have "Details" menu item (similar to the one that appears in the homepage when clicking on a show). It should also have "Dismiss" item, but that's not the purpose of this ticket.

### Screenshots

Example of the menu when a show is viewed from the library screen
![Image](https://github.com/user-attachments/assets/793d5506-7ef2-41b8-8db5-b5f92c4c7bc0)

Example of the menu when a show is viewed from the home page
![Image](https://github.com/user-attachments/assets/05147f1b-17c0-4c45-89d7-4da633e370e8)

### TV (if applicable)

Device: LG TV
OS: WebOS 24
Stremio: 1.6.0
Theater: 1.8.1

### Logs

```shell

```

### Notes

related to ticket https://github.com/Stremio/stremio-features/issues/1317#issuecomment-3084212707

**Comment by freezenification** [comment]
Having a similar issue on the Samsung app!

**Comment by freezenification** [comment]
Would absolutely love to see this fixed at some point! 🙌

**Comment by levynir** [comment]
Still happens on some shows in 1.9.2. However, it's not consistent. 

![Image](https://github.com/user-attachments/assets/7b3eb2a0-8b53-407f-8946-5f09a81e7c38)
