### ISSUE TITLE
[MacOS] Stremio 5 playback colors are muted / washed out

### ISSUE THREAD

**Issue by lothar-cell** [Stremio/stremio-bugs#1940]
### Stremio Platform

MacOS

### Describe the bug

Stremio v4 had oversaturated colors, v5 has muted colors.

I'm not an expert, but there should be a protocol in MacOS called ColorSync, which determines correct colors, just try to use that? v4 has ignored it completely and v5 is using it incorrectly?

Playback colors are perfect when using IINA as external player, in-app playback and interface is still washed out.

It's not about HDR - UI, movie posters are washed out too.

### To Reproduce

Launch Stremio 4 - UI colors are oversaturated.
Launch Stremio 5 - UI colors are washed out.

### Expected behavior

Colors should be accurate, in sync with the system.

### Screenshots

In-app: <img width="1680" height="1050" alt="Image" src="https://github.com/user-attachments/assets/0c7205ba-8d47-4e10-b66b-700649426e47" />
(colors are muted and image is softer, less well defined)

IINA: <img width="1680" height="1050" alt="Image" src="https://github.com/user-attachments/assets/56f451a6-becf-4903-89cb-3a93e440fb02" />
(colors are accurate and image is better defined in IINA without any filters used)

### App Version

v5

### Device Info

Macbook air M1

### OS Version

MacOS 15.7.2

### Logs

```shell

```

**Comment by kKaskak** [comment]
any examples?

**Comment by kKaskak** [comment]
in the ui

**Comment by lothar-cell** [comment]
Not sure if the UI problem still applies, seems alright?

**Comment by kKaskak** [comment]
This was fixed

**Comment by lothar-cell** [comment]
It was not fixed, I'm sorry. Playback colors are still off.

<img width="1680" height="1050" alt="Image" src="https://github.com/user-attachments/assets/f83863c3-d9a4-4404-bffa-25e419b6e7f7" />


<img width="1680" height="1050" alt="Image" src="https://github.com/user-attachments/assets/a384be21-33b1-4f40-9c1d-20b4e6dc1ebd" />

**Comment by kKaskak** [comment]
> It was not fixed, I'm sorry. Playback colors are still off.
> 
> <img width="1680" height="1050" alt="Image" src="https://github.com/user-attachments/assets/f83863c3-d9a4-4404-bffa-25e419b6e7f7" />
> 
> 
> <img width="1680" height="1050" alt="Image" src="https://github.com/user-attachments/assets/a384be21-33b1-4f40-9c1d-20b4e6dc1ebd" />

What version are you on? All colours display correctly as expected both HDR and non HDR for me.

**Comment by kKaskak** [comment]
<img width="1728" height="1082" alt="Image" src="https://github.com/user-attachments/assets/000c9597-31e2-45d5-90c4-916dcf634bff" />

**Comment by kKaskak** [comment]
ah i see maybe you tried non hdr stream there is a slight difference indeed

**Comment by kKaskak** [comment]
try hdr stream instead, i will check if i can improve it for non hdr streams as well, there seems to be some sort of difference with color grading

**Comment by kKaskak** [comment]
fix coming in next release closing

**Comment by lothar-cell** [comment]
Sorry for not replying earlier, I'm traveling at the moment, and don't have access to HDR screen. Hopefully playback will be fixed in next release. Thank you!

**Comment by kKaskak** [comment]
> Sorry for not replying earlier, I'm traveling at the moment, and don't have access to HDR screen. Hopefully playback will be fixed in next release. Thank you!

Yeah release is ready will be pushed as early as Monday next week.

**Comment by kKaskak** [comment]
@lothar-cell https://dl.strem.io/stremio-shell-macos/v5.1.23/Stremio_arm64.dmg please install this preview version which should fix the issue you were having

**Comment by lothar-cell** [comment]
I tried it, thanks. Colour seem to be correct now, there's some difference in tone compared to IINA, using HDR content with SDR playback.

in-app:
<img width="1680" height="1050" alt="Image" src="https://github.com/user-attachments/assets/a205f2ec-28aa-48f0-bfbd-584c3bdcfd3c" />

IINA:
<img width="1680" height="1050" alt="Image" src="https://github.com/user-attachments/assets/d2089774-22de-40ea-8861-904b69b3ae91" />

in-app:
<img width="1680" height="1050" alt="Image" src="https://github.com/user-attachments/assets/573f8277-afe0-4989-a4bf-7803cbe8c599" />

IINA:
<img width="1680" height="1050" alt="Image" src="https://github.com/user-attachments/assets/7e7d07bc-3817-4315-b37f-f539b6b39d46" />

in-app:
<img width="1680" height="1050" alt="Image" src="https://github.com/user-attachments/assets/b66333b1-3f9c-49de-8bcb-aa2440acb23b" />

IINA:
<img width="1680" height="1050" alt="Image" src="https://github.com/user-attachments/assets/438ed115-8749-431c-99a1-e1138a808fbb" />


SDR content seem to be the same:

in-app
<img width="1680" height="1050" alt="Image" src="https://github.com/user-attachments/assets/dc5ba249-0a60-4c18-a428-e3d2feac9d6f" />

IINA:
<img width="1680" height="1050" alt="Image" src="https://github.com/user-attachments/assets/315e1fca-798a-487f-ab85-e725f56b0ea3" />

**Comment by kKaskak** [comment]
> I tried it, thanks. Colour seem to be correct now, there's some difference in tone compared to IINA, using HDR content with SDR playback.

this is normal since we use custom settings idea is that color are not washed out we cant be 1/1 to IINA in everything haha all colors display correctly now as i can see, tone mapping might differ between playback

HDR should 1/1 match the IINA one i can see all streams you tried are SDR

**Comment by lothar-cell** [comment]
SDR screen, yes, HDR content, except Spongebob haha.
