### ISSUE TITLE
Stremio crashes on Android tv under 1 minute

### ISSUE THREAD

**Issue by Hallanvaara** [Stremio/stremio-bugs#1948]
### Stremio Platform

Philips TV Android

### Describe the bug

On my Philips android tv (not Philips own Android os) stremio suddenly crashes under 1 minute after launching. It worked fine week ago and I noticed stremio got update on tv so it might be the cause?

Until crash app works just like it's suppose to. Tried reinstalling but app crashes still just as fast so fast I can't even log back in after reinstalling.

### To Reproduce

Launch stremio on Philips android tv
Wait or do anything, doesn't matter
Crash back to tv menu

### Expected behavior

Launch the app and watch videos, or at least so that app doesn't crash on its own

### App Version

1.8.0

### Device Info

Tpm171e / pus8503

### OS Version

8

### Logs

```shell

```

**Comment by akin-fagbohun** [comment]
Can confirm this is also happening for me on a Sony Bravia exactly as described - It worked fine yesterday on this particular tv. I just checked another tv and it currently works. Both are on the same  `v1.8.0` version. I'll return to update if that status changes.

**Comment by Cinogen49** [comment]
Can confirm this happens on a sony device as well.

**Comment by Tetriminos** [comment]
Can confirm, Philips Android TV v1.8.0

**Comment by djangoamidala** [comment]
When the problem will be solved please? Same problem on sony bravia

**Comment by TRtomasz** [comment]
IF anyone of you can provide adb logs for that crash we would be grateful

**Comment by polyrenn** [comment]
Same issue, Bravia Tv. Installed v1.5.x
Seems stable for now.
Will check crash logs if the issue pops up again

**Comment by Hallanvaara** [comment]
> IF anyone of you can provide adb logs for that crash we would be grateful

I have no idea how to do that, especially on tv

**Comment by polyrenn** [comment]
> > IF anyone of you can provide adb logs for that crash we would be grateful
> 
> I have no idea how to do that, especially on tv

Debug with Adb over network

**Comment by Hallanvaara** [comment]
> > > IF anyone of you can provide adb logs for that crash we would be grateful
> > 
> > 
> > I have no idea how to do that, especially on tv
> 
> Debug with Adb over network

I'm stupid civil engineer so this tells me nothing. Googling what this gibberish means results in:

1. install SDK tools on PC https://developer.android.com/tools/releases/platform-tools
2. Enable adb debugging on TV (have to check that out)
3. Download android studio and install it too
4. Go through long list of stuff according https://developer.android.com/tools/adb
5. ???
6. Profit and maybe logs

Anywhere close?

**Comment by MegaSp00n** [comment]
+1 on a Sony Bravia. Fresh install of app and factory reset of TV made no difference

**Comment by djangoamidala** [comment]
Yes Sony Bravia so sad.. i am using cast with my macbook air m1, I hope the problem will be solved soon..

**Comment by Lloytron** [comment]
Can confirm this happens on my Philips Android TV exactly as described.

Even with a fresh install it crashes even before I can log in.

The only way round it is to uninstall, reinstall 17.4.0 and disable auto updates of apps

**Comment by TRtomasz** [comment]
@Hallanvaara  basically all you have to do is install android studio, enable developer mode, enable remote debugging on your TV and connect android studio to your TV which can be done easily. And then it will show logs, but i guess we will have to wait for someone who is skilled enough to do this.

**Comment by Tetriminos** [comment]
Hi, it was a hassle setting up because USB adb doesn't really work with my Philips (and the TV is slooow).

Here are stremio only adb logs:

[stremio_crash.log](https://github.com/user-attachments/files/23907146/stremio_crash.log)

Let me know if I can be of more help.

EDIT: I ran it twice, so I'm giving the second run of logs too.

[stremio_crash2.log](https://github.com/user-attachments/files/23907224/stremio_crash2.log)

**Comment by TRtomasz** [comment]
@Tetriminos  did you install app from play store?

**Comment by Tetriminos** [comment]
Yes sir, `installer=com.android.vending`.

**Comment by Tetriminos** [comment]
If you make a potential bugfix version, I can sideload it and verify it works before you push it to the store.

**Comment by akin-fagbohun** [comment]
> > > IF anyone of you can provide adb logs for that crash we would be grateful
> > 
> > I have no idea how to do that, especially on tv
> 
> Debug with Adb over network

The file is a little large and I don't have the bandwidth right now to scan it for PII, but here's the gist. 

  Root Cause: `java.lang.ClassNotFoundException: Didn't find class "java.lang.ClassValue"`

My tv is running: Android 8.0.0 (Oreo) on SDK 26

**Comment by TRtomasz** [comment]
@Tetriminos  what is android version of your device?

**Comment by Tetriminos** [comment]
8.0.0, with the kernel being 3.10.79
Last security patch is from January 2021.

**Comment by TRtomasz** [comment]
@Tetriminos you can try this app https://drive.google.com/file/d/16C-81gFRgxp3SSmmXp8l-PymXeGtP8fA/view?usp=sharing

**Comment by Tetriminos** [comment]
Instant crash.

[stremio_crash3.log](https://github.com/user-attachments/files/23914144/stremio_crash3.log)

**Comment by TRtomasz** [comment]
thanks @Tetriminos  made one more build https://drive.google.com/file/d/1iLXYbGR213QkYpy15shKm5eG_BvEGVco/view?usp=sharing

**Comment by Tetriminos** [comment]
Instant crash once more

[stremio_crash4.log](https://github.com/user-attachments/files/23957583/stremio_crash4.log)

**Comment by LeoLeal** [comment]
Can confirm this also happens on my Philips TV same model as OP.

Is there a way to rollback to previous version? It was working fine and now I feel like I'm wasting debrid subscription time. 🥲

**Comment by Hallanvaara** [comment]
> Can confirm this also happens on my Philips TV same model as OP.
> 
> Is there a way to rollback to previous version? It was working fine and now I feel like I'm wasting debrid subscription time. 🥲

You can find older version online and install it with USB. I think? Downloaded file but haven't got the time to install or try to get crash logs like tetriminos kindly has

**Comment by TRtomasz** [comment]
@Tetriminos  thanks for checking again, made another version - https://drive.google.com/file/d/1yKJLd7ZDjnFCqqev2a-tOafzdw8kGq7y/view?usp=sharing

**Comment by Tetriminos** [comment]
Same:

[stremio_crash5.log](https://github.com/user-attachments/files/23962779/stremio_crash5.log)

**Comment by Lloytron** [comment]
> Can confirm this also happens on my Philips TV same model as OP.
> 
> Is there a way to rollback to previous version? It was working fine and now I feel like I'm wasting debrid subscription time. 🥲

You have to download and install the previous APK. You can do it like this;
1) Download the Downloader App on your TV from the Google Play Store
2) Go to APK Mirror using Downloader Browser
3) Download and install the APK Mirror Package Manager
4) Using Downloader still, find Stremio Android TV version 1.7.4 and download the APKM file
5) Open the APKM file in the APK Mirror Package Manager - follow the instructions to then install.

**Comment by Lloytron** [comment]
> Same:
> 
> [stremio_crash5.log](https://github.com/user-attachments/files/23962779/stremio_crash5.log)

I don't have the ability to take logs but I can confirm I see exactly the same. When launching the APP I see the Stremio Logo (For much longer than usual) and then it crashes. The original version did actually show the dashboard or login screen but the updates here dont get that far.

**Comment by TRtomasz** [comment]
Weird, same error thanks for checking @Tetriminos  https://drive.google.com/file/d/1faEKo7NH78il8v8gZxlSOUACcWsU2gbW/view?usp=sharing just in case i uploaded wrong one here is uploaded it  again making sure it was indeed correct version

**Comment by TRtomasz** [comment]
I made a new version you can find it here - https://drive.google.com/file/d/1W1t-7oJjtIeLmrqmrc2tnreJ3pL-yGXO/view?usp=sharing

**Comment by Tetriminos** [comment]
Couldn't capture app start for some reason.

Now the behaviour is similar as at the start of the thread. I can see the Stremio dashboard before the crash now.

[stremio_crash6.log](https://github.com/user-attachments/files/23964556/stremio_crash6.log)
[stremio_crash7.log](https://github.com/user-attachments/files/23964557/stremio_crash7.log)

**Comment by Crankster619** [comment]
Hello, just chiming in to say I have the same issue on my Philips TV. I installed Stremio version 1.7.0 which still works fine.

Model: Philips 65PUS8602/12
Chassis: TPM171E
OS: Android TV 8.0
Stremio Version (Failing): v1.8.0

**Comment by LeoLeal** [comment]
From the logs It looks like FileSystem permission issues? Maybe These Android TVs with Android 8 have a different set of permissions available for the apps?

> 12-05 16:37:28.261 32309 32449 I zygote  : Rejecting re-init on previously-failed class java.lang.Class<kotlinx.coroutines.internal.ClassValueCtorCache$cache$1>: java.lang.NoClassDefFoundError: Failed resolution of: Ljava/lang/ClassValue;
> 12-05 16:37:28.261 32309 32449 I zygote  :   at boolean okio.NioSystemFileSystem$$ExternalSyntheticApiModelOutline0.m(java.nio.file.attribute.BasicFileAttributes) (D8$$SyntheticClass:0)
> 12-05 16:37:28.261 32309 32449 I zygote  :   at okio.FileMetadata okio.NioSystemFileSystem.metadataOrNull(java.nio.file.Path) (NioSystemFileSystem.kt:51)
> 12-05 16:37:28.261 32309 32449 I zygote  :   at okio.FileMetadata okio.NioSystemFileSystem.metadataOrNull(okio.Path) (NioSystemFileSystem.kt:35)
> 12-05 16:37:28.261 32309 32449 I zygote  :   at okio.FileMetadata okio.ForwardingFileSystem.metadataOrNull(okio.Path) (ForwardingFileSystem.kt:159)
> 12-05 16:37:28.261 32309 32449 I zygote  :   at boolean okio.internal.-FileSystem.commonExists(okio.FileSystem, okio.Path) (FileSystem.kt:41)
> 12-05 16:37:28.261 32309 32449 I zygote  :   at boolean okio.FileSystem.exists(okio.Path) (FileSystem.kt:41)
> 12-05 16:37:28.261 32309 32449 I zygote  :   at void okio.internal.-FileSystem.commonCreateDirectories(okio.FileSystem, okio.Path, boolean) (FileSystem.kt:49)

**Comment by TRtomasz** [comment]
No this is not filesystem permission issue, android tooling is at fault here and at the moment there is nothing we can do to fix it.
https://issuetracker.google.com/issues/466978531

**Comment by LeoLeal** [comment]
Oh i see they are communicating with you. What changed between 1.7.4 and 1.8.0? When I rolled back to 1.7.4 It started working again (but now I dont have the Like/Love feature which I was looking forward to).

Thank you for the great work, BTW. I would like to leave the apreciation for the time and love you've been putting into this.

**Comment by djangoamidala** [comment]
I personally bought a second-hand Chromecast HD for $10. It’s much better than the Android TV on my Sony Bravia OLED. There’s no problem with it, and I don’t think there will be. Our TV is running Android 8, which is very old now.

**Comment by deepspacehub** [comment]
Hello, just chiming in to say I have the same issue on my Sony Bravia TV. I installed Stremio version 1.7.4 which still works fine.

Model: Sony KD-65XD7505
OS: Android TV 8.0
Stremio Version (Failing): v1.8.0

Is there any possibility to stop the app from Auto-Updating without losing the option to auto-update the other apps or disconnect from LAN (bc. streaming would then not be possible anymore)?

**Comment by Lloytron** [comment]
> Hello, just chiming in to say I have the same issue on my Sony Bravia TV. I installed Stremio version 1.7.4 which still works fine.
> 
> Model: Sony KD-65XD7505 OS: Android TV 8.0 Stremio Version (Failing): v1.8.0
> 
> Is there any possibility to stop the app from Auto-Updating without losing the option to auto-update the other apps or disconnect from LAN (bc. streaming would then not be possible anymore)?

You can't disable specific apps from auto updating. You can only disable ALL apps, you can go this in the Play Store Settings.

**Comment by reowasnotavailable** [comment]
The Google issuetracker was closed with "won't fix (not reporoducible)" means we won't see thisw working again and downgrading is the only way? Still don't get why it's a Google problem, if downgrading to 1.7.4 works.

**Comment by TheIceBadger** [comment]
Also having this issue on a Philips android TV after updating to 1.8.0
(To clarify, I notice the same symptoms too with long time stuck at logo, and then a brief view of the dashboard)

Though I noticed that when it "crashes" that it still shows as running in the app manager (settings sidebar)
If I then force stop the app there, wait a bit for it to properly stop, then open it again it works fine, until I leave the app and return, then it "crashes" again. 

Wonder if this workaround works for others too? 

- Open app, let it crash
- Open app manager (Philips tv has it in the settings sidebar)
- find stremio and force stop
- wait until force stop text is gone
- Open app again

Now it also opens faster, not sitting on logo as long and then seems to just work fine.

**Comment by varanbey** [comment]
> > Can confirm this also happens on my Philips TV same model as OP.
> > Is there a way to rollback to previous version? It was working fine and now I feel like I'm wasting debrid subscription time. 🥲
> 
> You have to download and install the previous APK. You can do it like this;
> 
> 1. Download the Downloader App on your TV from the Google Play Store
> 2. Go to APK Mirror using Downloader Browser
> 3. Download and install the APK Mirror Package Manager
> 4. Using Downloader still, find Stremio Android TV version 1.7.4 and download the APKM file
> 5. Open the APKM file in the APK Mirror Package Manager - follow the instructions to then install.

This is the best way for us to watch on Stremio.

**Comment by TRtomasz** [comment]
Issue is reopened. In the meantime we released 1.8.1 you can get it on our website and maybe somehow it got fixed there.

**Comment by Lloytron** [comment]
Sadly for 1.8.1 its still the same, loads up and then crashes after about 10 seconds

**Comment by djangoamidala** [comment]
You should buy chromecast or firestick because our tv are running on a very old android version..

**Comment by jenhsun** [comment]
I can confirm version 1.8.1 does fix my Android TV issue on "Failed to create cache directory for temporary files". Many thanks.

PS. Install the APK download from Stremio site, not from Google Play store.

PPS. When doing debugging, make sure you reset your Android TV machine back to factory default and install APK again. It's because Android/Linux OS do not have good "Uninstaller/Cleaner APP" available, like some similar apps for MacOS or Windows to trace back and deeply remove all installed app's from vary paths. Unless there do have some good cleaner apps that I don't know yet.

**Comment by LeoLeal** [comment]
Tried APK download link, Play Store APK and APKMirror for 1.8.1 and the issue is the same for all the 3 options. Came back to 1.7.4 again.

Phillips TPM171E at AndroidTV 8

**Comment by TRtomasz** [comment]
Hello, hny everyone, we prepared another version in attempt to fix the issue please check it out https://drive.google.com/file/d/1DyDgZt18HKdEukecGZr5noqyzZZRO5tW/view?usp=sharing

**Comment by Tetriminos** [comment]
I won't be home until Monday. If it still crashes I'll do my best to provide logs then.

**Comment by Lloytron** [comment]
Unfortunately this didnt work for me, its just the same, crashes after 10 seconds.

**Comment by djangoamidala** [comment]
Ask GPT it will be easier to solve the problem 🤣🤣

**Comment by lchlnwlls** [comment]
1.8.2 RC1 still crashing on Android TV 8.0.0

**Comment by TRtomasz** [comment]
Thanks for checking it!

**Comment by reowasnotavailable** [comment]
Any news?

**Comment by awhdejongh** [comment]
I have the same issue on a Sony Bravia TV (xbr-55x850d 2016), running Android 8. I was on version 1.8.1 and everything was fine. I updated to the latest version via the Google Play Store (1.9.2) and started experiencing Stremio crashing every time after 5-10 seconds of opening it. It returns to my homescreen.

After some digging online, I found that uninstalling updates and disabling the app "Android System WebView" worked. I was able to boot up Stremio and haven't had any issues yet. Maybe this helps for the devs to figure out what the cause is. 

Love your app and thanks for all your hard work!!

**Comment by Lloytron** [comment]
Thanks but I don't think this is the same issue, no version after 1.7.4 is
working on Android 8.

I tried the suggested fix but unfortunately this didn't make any difference.

**Comment by awhdejongh** [comment]
Sorry to hear that. It is indeed a very strange issue, but what do you mean by "no version after 1.7.4 is working on Android 8"? Version 1.8.1 and all previous versions worked great on my TV.  

Another thing that you can try and has also worked for me, is to add some of the catalogs of Stremio (continue watching for instance) to your Home Screen and launch an episode/movie directly from there. I was able to open and browse Stremio normally after this.

**Comment by reowasnotavailable** [comment]
With 1.8.0 (the Version after 1.7.4) Stremio stopped working on quite a few ATVs with Oreo. The Homescreen workaround worked Sometimes until they dropped 1.9 which even killed this.

Since then it's unusable.

**Comment by yo-da-man** [comment]
> I have the same issue on a Sony Bravia TV (xbr-55x850d 2016), running Android 8. I was on version 1.8.1 and everything was fine. I updated to the latest version via the Google Play Store (1.9.2) and started experiencing Stremio crashing every time after 5-10 seconds of opening it. It returns to my homescreen.
> 
> After some digging online, I found that uninstalling updates and disabling the app "Android System WebView" worked. I was able to boot up Stremio and haven't had any issues yet. Maybe this helps for the devs to figure out what the cause is.
> 
> Love your app and thanks for all your hard work!!

Thanks for suggesting this workaround. 

I tried this on my Sony Bravia XBR-75X940D which runs on Android 8.0 but the workaround - to uninstall Android System Webview - did not work for me. My Stremio 1.9.2 app would still crash after 5-10 seconds. I had to uninstall v1.9.2 and reinstall v1.7.4. 

I had logged a [separate bug](https://github.com/Stremio/stremio-bugs/issues/2210) not realizing this one already existed but that was closed citing the issue is on Android’s side. Does anyone have a link to the related Android bug? Perhaps we can push Android folks to fix it.

**Comment by kevingoris** [comment]
In android tv still crashes every time after a fresh start of the app.
I have to open it a couple of times and try to move around the app or try to force a video to start. 
A couple of times, until it won't crush. And will work fine. 
But after watching some episodes and the app gets buggy (like it stops cacheing the video as good as it supposed)
So I have to force close the app and start the fight again for it to not crash and work again. 
I'm using the last version of the android tv app.

**Comment by TheIceBadger** [comment]
> In android tv still crashes every time after a fresh start of the app. I have to open it a couple of times and try to move around the app or try to force a video to start. A couple of times, until it won't crush. And will work fine. But after watching some episodes and the app gets buggy (like it stops cacheing the video as good as it supposed) So I have to force close the app and start the fight again for it to not crash and work again. I'm using the last version of the android tv app.

I had this ___exact___ problem on my Philips Android TV when going to 1.8.0 (and 1.8.1) not updated from that yet as I just see people having a lot of issues with newer versions.
However, will say that after updating to 1.8.1, then clearing cache and deleting all data and stuff, it seems to be behaving ok with only rare crashes, usually only after long usage periods without restarts and usually when on the video loading screen.

**Comment by kevingoris** [comment]
> > In android tv still crashes every time after a fresh start of the app. I have to open it a couple of times and try to move around the app or try to force a video to start. A couple of times, until it won't crush. And will work fine. But after watching some episodes and the app gets buggy (like it stops cacheing the video as good as it supposed) So I have to force close the app and start the fight again for it to not crash and work again. I'm using the last version of the android tv app.
> 
> I had this _**exact**_ problem on my Philips Android TV when going to 1.8.0 (and 1.8.1) not updated from that yet as I just see people having a lot of issues with newer versions. However, will say that after updating to 1.8.1, then clearing cache and deleting all data and stuff, it seems to be behaving ok with only rare crashes, usually only after long usage periods without restarts and usually when on the video loading screen.

Yeah, in my case it works quite well, videos load faster. They bought back showing loading info for seeds too. 
But my main issues are that at the start of the app that keeps crashing indefinitely and the accumulation of cache without really knowing it's that. And having to clean the cache from the system or having to force close the app. 
There should be some kind of automatic cache purge. And don't know how to fix the start.

**Comment by Lloytron** [comment]
I think you guys are experiencing a similar but different issue than the
one reported here.

I have tried every release version and all the private ones shared here.

Clearing cache, using shortcuts, reinstall, full clear downs, I've tried
everything and it's always the same. A longer loading time, and then crash
after ten seconds, every time.

**Comment by kevingoris** [comment]
> I think you guys are experiencing a similar but different issue than the
> one reported here.
> 
> I have tried every release version and all the private ones shared here.
> 
> Clearing cache, using shortcuts, reinstall, full clear downs, I've tried
> everything and it's always the same. A longer loading time, and then crash
> after ten seconds, every time.
> […](#)

I do have the start up issue, that it close after less than a minute. Don't know if 10 seconds. But I have to open it several times and move around or mostly every time if I can play a video fast enought it won't close. Not always work, but after couple of trys it will start working no problem.

**Comment by Lloytron** [comment]
Right, but that's the point, it's possibly related but it's a different
issue.

It hard crashes 10 seconds every single time. I don't have enough time to
login on fresh installs. On updated installs there is not enough time to
click around and certainly not enough time to start playing a video. I've
timed it, it's ten seconds every single time.

There's even a handy timer on the login screen!

**Comment by kevingoris** [comment]
> Right, but that's the point, it's possibly related but it's a different
> issue.
> 
> It hard crashes 10 seconds every single time. I don't have enough time to
> login on fresh installs. On updated installs there is not enough time to
> click around and certainly not enough time to start playing a video. I've
> timed it, it's ten seconds every single time.
> 
> There's even a handy timer on the login screen!
> […](#)

Then it's different, but in the same realm as you say. 
Mine will load up to the home screen and after some time will crush. I could try to time it. But I rather just force it to work, choosing something fast enought.

Don't know if I should open an other issue. 
Can't remember the specific version it started to do that. But I like how it's working aside from that.

**Comment by TheIceBadger** [comment]
Could also be same issue, behaving slightly different on different hardware, a bit more ram here, a bit better processor there and suddenly the same issue has different symptoms.
It all started with the 1.8.0 update, with crashing, mine would crash constantly after a few seconds, same thing could hardly log in, but could sometimes get past it with a force quit and cache clearing, sounds a lot like the same issue, but after clearing the cache, deleting all the files and stuff, 1.8.1 has been ok. Maybe my tv just has a bit more spare ram cause I disabled all the bloat and have kept the old android tv ui stuff as the new ones are full of ads and just bloated code, it runs way way slow compared to what the tv came with.

**Comment by dbancora** [comment]
Same problem here with TCL android TV.
Open Stremio app, and then, after 10 seconds, the app crash.

**Comment by reowasnotavailable** [comment]
Yep, 1.10.0-rc2 Crashes after 10s. Don't think we'll ever see this work on "our" Models again.

As soon as my RD sub runs Out I'll Take stremio to the grave. We had a short but good time.

**Comment by njuart** [comment]
Got same issue on my Philips TV with Android 8.0. Crash after 10 seconds. However, I've managed to launch it twice, I can't understand what exactly was different during these 2 times, just noticed that it loaded much faster, because before crash it gets stuck on Logo splash screen for some time, than loads and crashes after 9-10 seconds. I've tested it on

1.10.0 rc4
1.9.10
1.8.4
1.8.1

1.7.4 is the latest version that works properly, so had to rollback to it.

**Comment by TRtomasz** [comment]
we have made a new version. Please try it out https://dl.strem.io/android/v1.9.11-androidTV/com.stremio.one-1.9.11-11049226-armeabi-v7a.apk

**Comment by Lloytron** [comment]
It works!!!

Just did an initial test and I had to authenticate.... Previously it's
always crashed before I could get to log in.

I have logged in, browsed around, started a few videos, it's working so far!

Thank you so much for your persistence!

**Comment by gl0b** [comment]
I confirm that the crashes disappeared from TPM171E running on Android 8, congrats for the fix!🔥

**Comment by njuart** [comment]
> we have made a new version. Please try it out https://dl.strem.io/android/v1.9.11-androidTV/com.stremio.one-1.9.11-11049226-armeabi-v7a.apk

Yup! No crash detected so far. Great news. Thx

**Comment by dbancora** [comment]
Hi, can someone test this version on TCL TV running android TV? 

Thanks!

**Comment by kevingoris** [comment]
> Hi, can someone test this version on TCL TV running android TV?
> 
> Thanks!

It didn't crash on TCL TV with android 9.
Did have to uninstall and reset the TV to make it work. 
When installed over the previous versions it didnt past the logo. Or crashed. Even with clearing the cache. 
But it finally worked. 
Great that that problem its fixed. 

What was causing it?

**Comment by reowasnotavailable** [comment]
> I confirm that the crashes disappeared from TPM171E running on Android 8, congrats for the fix!🔥

I can second this. Finally. 🤟🏻

**Comment by awhdejongh** [comment]
I can confirm, with version 1.9.11 no crashes on Sony bravia xbr-55x850d running android 8.0 oreo. 
Thanks for all the hard work devs!

**Comment by TRtomasz** [comment]
happy to close that one thanks for testing it before the release
