### ISSUE TITLE
Stremio doesn't allow Windows 10 to turn off display or go to sleep while movie is paused

### ISSUE THREAD

**Issue by vipdude** [Stremio/stremio-bugs#253]
When a movie is on pause in Stremio, PC won't turn off display or go to sleep. It happens in all cases - window in foreground, in the background, or even closed. I have to quit the movie (by going back to the board) to get the PC to turn off display or sleep.

Stremio version is 4.4.77
OS is Windows 10 build 19041.685

Powercfg /requests shows stremio in the DISPLAY section until the movie is quit.

**Comment by GitExploraa** [comment]
i can confirm that this is still happening, and unfortunately there have been no official answers

**Comment by TRtomasz** [comment]
Should be fixed with the latest release

**Comment by dalmackay** [comment]
This is still happening, newest Stremio v5 on windows. system will never sleep with Stremio running
