### ISSUE TITLE
Stremio desktop: Subtitles not automatically active

### ISSUE THREAD

**Issue by dratiom** [Stremio/stremio-bugs#403]
Hi,

In my settings i've specified that my default subtitles should always be in English. When launching a movie/tv show i need to activate the translation (on/off button bottom right + select the language & subtitle number).

I have the latest version of stremio 4. 4.159 and Windows 10

Any idea what the root cause here could be.

thank you!

**Comment by TRtomasz** [comment]
Does it happen only for some kind of subtitles maybe only embedded or only addon subtitles?

**Comment by dratiom** [comment]
Add on subtitles mostly, it never switches by default to the one specified (English)

**Comment by bt4ibwem8** [comment]
I have same issue on Win7 system. Both embedded and addon subtitles are allways OFF and i have to turn on it manually (for movies and series). I am on 4.4.159 desktop version. Of course i have enabled preffered subtitles language in the settings.
I also have same issue on Android smartphone. Hower on Android TV version the subtitles are loaded correctly automatically...

**Comment by PadreToio** [comment]
I have the same issue on Win 11 (2 different computers with the same behaviour). 
Both embedded and add-on subtitles are always OFF! I have to manually turn them ON each time I launch a video. If I restart the app or a video, the same issue occurs. My default subtitle language setting is set to "Portuguese" and I have tried more languages like English and Brazilian Portuguese.  
 
Stremio version 4.4.159.

**Comment by TRtomasz** [comment]
@PadreToio  please provide us example of video/stream where automatic embedded subtitles does not woork

**Comment by PadreToio** [comment]
> @PadreToio please provide us example of video/stream where automatic embedded subtitles does not woork

The first image shows that the default subtitle language is configured and set to Portuguese.

![1 - Default Subtitle Language](https://user-images.githubusercontent.com/13244203/224325101-75202dac-c992-4bab-827e-cd7795876b58.png)

The second image shows that embedded subtitles are not enabled by default. Portuguese does not show up in the 1st screenshot, but it's there on the list, I had to scroll further down. 
![2](https://user-images.githubusercontent.com/13244203/224325864-7f031e60-17c3-46b7-92eb-aecdb9e4b897.png)
![2 1](https://user-images.githubusercontent.com/13244203/224326179-a5f6e26f-adeb-4fca-92a4-6b9697623efe.png)

The final image shows a movie without embedded subtitles, but with the same behavior. Subtitles set to OFF by default.

![4 - Drive My Car - Subtitle OFF](https://user-images.githubusercontent.com/13244203/224325173-0003e074-80fc-422e-b42f-40e3f7674398.png)

**Comment by bt4ibwem8** [comment]
I have tried it now also on another operating systems (Linux Fedora desktop and Android smartphone). Issue is same and for all movies and series... Then i tried different languages subtitles and they worked.
So this bug is related only to **czech** and **slovakian** subs (probably also few another) regardless of operating system they are running on.

**Comment by jnmbk** [comment]
I have the same problem with Turkish language on Mac OS.

**Comment by bt4ibwem8** [comment]
The question to the devs:
Did you already identified the cause of this issue?

**Comment by antiphon0** [comment]
This is still happening. I am only using OpenSubtitles addon.

**Comment by bt4ibwem8** [comment]
@antiphon0
which language are you using? I saw some of them are good...

**Comment by sammyke007** [comment]
Still an issue...

**Comment by pcgreen-john** [comment]
Still a very annoying issue, especially if you binge watch a series, means you always have to manually enable subtitles every time you start (or resume) something. Works flawlessly on my android tv box. Considering how really good Stremio is, I'm surprised this  issue hasn't been resolved. Windows 10, Greek subtitles (English also problematic), exclusively Real Debrid sources. Doesn't make a difference if there's embedded subs or not.

**Comment by batuhankrmn** [comment]
Still an issue on Windows 11 desktop app. Do you guys know any fix for this?

**Comment by GKid94** [comment]
Still a problem
![Screenshot 2024-04-24 080331](https://github.com/Stremio/stremio-bugs/assets/18757054/980c984c-6d35-4b86-b071-9d2b9869762f)
![Screenshot 2024-04-26 152152](https://github.com/Stremio/stremio-bugs/assets/18757054/79fcf6ba-2e0c-4409-8cad-d7e02b866cd6)

**Comment by PoBruno** [comment]
Same here, on all my devices, Android 13, Windows 11 and Ubuntu 20.04. Like everyone, I set my favorite subtitle, no matter which one, when I play any video, it comes with subtitles deactivated.

**Comment by fcakyon** [comment]
same happening on latest macos app

**Comment by azizhaboubi** [comment]
03 december 2024 still same problem no solution

**Comment by TRtomasz** [comment]
Closing as this issue should be fixed now in Stremio shell 5

**Comment by bt4ibwem8** [comment]
@TRtomasz 
i tried it now on web.stremio.com in Firefox and it is still broken

![Image](https://github.com/user-attachments/assets/00412875-50de-478a-871e-62b19ed91002)

**Comment by bt4ibwem8** [comment]
edit:
Also Chromium-based browsers do not work. Subtitles are off (for CZECH).
