### ISSUE TITLE
Disabeling "Notifications" from the system tray but the application turns it back on after restarting the app

### ISSUE THREAD

**Issue by pateldhruv1993** [Stremio/stremio-bugs#43]

**Comment by Ivshti** [comment]
Good observation, that should be fixed

**Comment by Tavish101** [comment]
Disabling Notifications doesn't disable them. I am still getting notifications for new episodes with the notifications turned off.

**Comment by TRtomasz** [comment]
I'm closing this. If it is still happening  in stremio 4 please let us know
