### ISSUE TITLE
ERROR_CODE_AUDIO_TRACK_INIT_FAILED

### ISSUE THREAD

**Issue by MrKaon** [Stremio/stremio-bugs#513]
ERROR_CODE_AUDIO_TRACK_INIT_FAILED on DTS and TRUEHD files even though audio and video keep playing on Android TV; Audio play OK with no problem but error massage will stay on screen.
Using CCwGT .

![PXL_20230830_205938666 MP](https://github.com/Stremio/stremio-bugs/assets/7486664/f2d87592-b48a-4fef-929d-d4b8123bf80f)

**Comment by SSwaggerSoulss** [comment]
I have the same problem. As a workaround I switched to default player - libVLC in the settings.

**Comment by jaruba** [comment]
it is already fixed in the hotfix release, but may take 1-2 days to reach full rollout

**Comment by sylverstream** [comment]
I still have this issue on ccwgtv @jaruba

Libvlc doesn't have the issue but has the issue that it stutters a little bit. Exoplayer plays fine except for this error. I'm on 1.6.2

**Comment by enko2974** [comment]
Still the same problem even with hotfix and with 1.6.2 on android tv 11.

**Comment by jaruba** [comment]
We are looking into this one, hopefully we will find the fix soon as it is hard to reproduce on our side. (doesn't happen on all devices)

**Comment by jaruba** [comment]
@MrKaon @SSwaggerSoulss @sylverstream @enko2974 We need more information about the setups you guys use and get this error on. Any information about what android tv devices you use, what tv brand you use, how old the tv, if you have any bluetooth or wired speakers / headphones connected and what kind of streams (are they surround? AAC? Dolby Digital? Dolby TrueHD?) would help a lot..

I have tried reproducing this on nvidia shield on a newer LG TV:

- tried many 5.1 and 7.1 streams, couldn't reproduce
- tried bluetooth headset, couldn't reproduce (Jabra Move, Jabra Elite, AirPods)
- tried changing "available formats" in the nvidia shield settings to "manual" (and all dolby audio settings disabled) and "none", couldn't reproduce
- tried enabling "tunnelled playback", couldn't reproduce

**Comment by sylverstream** [comment]
@jaruba thanks for investigating. I'm using a Chromecast with Google TV 4k (CCWGTV) 
Android 12.
Custom Projectivy Launcher. 

It mainly seemed to happen in 4k streams, not sure about audio codec as that wasn't always displayed. The weird thing is that the audio did work, so if the error would not show, there wouldn't be any issue. 

I've got a Philips sound bar connected to a Veon 4k TV via optical. So, sound goes from CCWGTV to TV to sound bar.
I also have a Vero 4k connected to a different HDMI input, never had issues in years.

Hope this helps.

**Comment by enko2974** [comment]
> @MrKaon @SSwaggerSoulss @sylverstream @enko2974 We need more information about the setups you guys use and get this error on. Any information about what android tv devices you use, what tv brand you use, how old the tv is, if you have any bluetooth or wired speakers / headphones connected and what kind of streams (are they surround? AAC? Dolby Digital? Dolby TrueHD?) would help a lot..
> 
> I have tried reproducing this on nvidia shield on a newer LG TV:
> 
> * tried many 5.1 and 7.1 streams, couldn't reproduce
> * tried bluetooth headsets, couldn't reproduce (Jabra Move, Jabra Elite, AirPods)
> * tried changing "available formats" in the nvidia shield settings to "manual" (and all dolby audio settings disabled) and "none", couldn't reproduce
> * tried enabling "tunnelled playback", couldn't reproduce

Hello , thank you for your interest on this, stremio is great app , the best i ever use , only missing some addon plus like torrentio with realdebrid support , with torrents.

My device that i use is xiaomi mi4k stick newest with android tv 11 , with the previos version of stremio 1.5.11 i havent have this problem , now its most with AAC soundtrack ,everytime. but sometimes and with dolby , but rare.
When i disable tunneled playback it reproduce fine , but the movie is stuttering every 10 seconds and yesterday evening throw me on lbc player in the middle of the movie.

I hope it will be fixed , if it can , thank you in advance

**Comment by jaruba** [comment]
@sylverstream @enko2974 thank you for answering! i (finally) managed to reproduce it based on both of your input by using a Chromecast 4K wGTV device and enabling tunnelled playback in the settings!

**Comment by enko2974** [comment]
> @sylverstream @enko2974 thank you for answering! i (finally) managed to reproduce it based on both of your input by using a Chromecast 4K wGTV device and enabling tunnelled playback in the settings!

Great , if you need someone for testing , im here , thank you working on this.

**Comment by enko2974** [comment]
> @sylverstream @enko2974 thank you for answering! i (finally) managed to reproduce it based on both of your input by using a Chromecast 4K wGTV device and enabling tunnelled playback in the settings!

Thank you,on playstore is version 1.6.3 and for now ,short time testing,is working great,no error,is fixed.
Thank you again

**Comment by jaruba** [comment]
@enko2974 yes, we're in the process of rolling out a new release with the fix (currently at 50%) it will still take about 2 days for full rollout, we will announce it publically in a few hours or so with a tech update blog post

**Comment by jaruba** [comment]
blog post is live: https://blog.stremio.com/stremio-tech-update-23-android-tv-desktop-mobile-fixes/
