### ISSUE TITLE
Unaired episodes are displayed in "Continue watching" despite having an air date

### ISSUE THREAD

**Issue by leahdrenalin** [Stremio/stremio-bugs#606]
**Describe the bug**
When watching an ongoing TV show and having caught up until the most recent aired episode, the Continue row shows the unaired upcoming episode even though it does have an air date in the metadata. 

**To Reproduce**
1) Mark all aired episodes of an ongoing show as watched (Tried with Last Week Tonight)
2) Go to Home -> Continue 
3) Last Week tonight is shown even though the next episode airs in December

**Expected behavior**
Do not show unaired episodes

**Comment by TRtomasz** [comment]
should be fixed now.

**Comment by DannieBGoode** [comment]
This is not fixed I have this exact issue both in Stremio web and on the Windows 10 app. Unaired episodes appear in the "Continue Watching" row

**Comment by brutalmurder** [comment]
> This is not fixed I have this exact issue both in Stremio web and on the Windows 10 app. Unaired episodes appear in the "Continue Watching" row

Any fix for this?

**Comment by Diazz72** [comment]
This behavior still persist :/
