### ISSUE TITLE
Samsung TV Error on subtitle: Could not load external subtitle

### ISSUE THREAD

**Issue by guimatheus92** [Stremio/stremio-bugs#637]
**Describe the bug**
I was watching TV Series and suddenly a subtitle could not load and I got an error message at the top "Could not load external subtitle". This happened often and I had to turn off my Samsung TV and wait fow a few minutes for the addon to work again by itself.

This is very annoying, because if I open Stremio on my Desktop it works just fine.

**Expected behavior**
Work addon as Desktop and stop errors regarding subtitles, it's SO annoying.

**TV:**
 - Device: Samsung QN60Q65BAGXZD
 - OS: 1602

**Comment by aonurgiray** [comment]
I have the same issue on my Samsung Q80B. Embedded subtitles are not showing a language and appearing like 0[embedded] 1[embedded].
Subtitles that show the language does not load most of the time with error "Could not load external subtitle". 
There's no option to align shifted subtitles like in PC also having subtitle version name would be a great improvement to have better sync.
One note, app UI is sometimes stuck unrecoverably. Especially while switching between menus.

**Comment by SubEdict** [comment]
On Samsung TV Q90T/Q95T, the message disappears after 3 seconds but the player GUI (Timeline, play/pause, etc.) is stuck and won't turn off. Nothing works except stopping the playing media.

**Comment by vikinatora** [comment]
Same issue on QE55Q80AATXXH using Stremio 1.0.1 - couldn't load external subtitles, then error message goes away but video controls don't dissapear ever.

**Comment by PsyGik** [comment]
> On Samsung TV Q90T/Q95T, the message disappears after 3 seconds but the player GUI ([Timeline, play/pause, etc.](https://www.reddit.com/media?url=https%3A%2F%2Fpreview.redd.it%2Fiiehl9r707bc1.jpg%3Fwidth%3D4000%26format%3Dpjpg%26auto%3Dwebp%26s%3Defbffba675f386ae568df64587b3d7fb7d67bd3c)) is stuck and won't turn off. Nothing works except stopping the playing media.

confirming the same behaviour. also there doesn't seem to be an option to disable subtitles from the main settings. i assumed that if that can be done, then at least the video controls will hide after a timeout. 

also an additional note, when the video controls are visible, (after the subtitle error is shown), pressing back does not dismiss it, rather closes the video player and goes back to the media list instead.

**Comment by bartolo112** [comment]
Anyone fixed that?

**Comment by SubEdict** [comment]
@bartolo112 Was fixed, work fine now, and if message do appears, it's only for a couple of seconds.

**Comment by bartolo112** [comment]
Hello,
On my TV  subtitles still doesnt work even after few second  There is an
informatioj but after it disappears, the subtitles areny working
Best regards

wt., 16 lip 2024, 13:14 użytkownik SubEdict ***@***.***>
napisał:

**Comment by SubEdict** [comment]
> but **after it disappears**, the subtitles areny working

If the subtitle **do** disappears, that's mean op #637 was fixed.

Your issue is different it's about some subtitles that either not supported or just broken, I see them sometimes, usually choosing different sub link works.

**Comment by TRtomasz** [comment]
External subitltes might not load due to multiple reasons, if it is happening all the time most likely there is an opensubtitles issue or your ip is being blocked by opensubtitles or cloudflare
