### ISSUE TITLE
Critical: Unable to Load Embedded Subtitles on Samsung TVs

### ISSUE THREAD

**Issue by p7a** [Stremio/stremio-bugs#641]
Dear Stremio Support Team,

I hope this message finds you well. I am writing to bring a critical bug to your attention regarding the Stremio app on Samsung TVs. This issue is preventing users from loading embedded subtitles, rendering them unable to watch content that lacks external subtitles.

**Bug Description:**
- **Severity:** Critical
- **Platform:** Samsung TVs
- **Bug Type:** Subtitle Loading Issue

**Issue Details:**
Users on Samsung TVs are experiencing a critical bug where they are unable to load embedded subtitles within the Stremio app. This problem is particularly troublesome as it impedes the ability to watch content that lacks external subtitles. The absence of embedded subtitles makes it challenging for users to enjoy the content properly, especially when external subtitles are not available or are out of sync.

**Steps to Reproduce:**
1. Launch the Stremio app on a Samsung TV.
2. Select any content without external subtitles.
3. Attempt to load embedded subtitles.

**Expected Result:**
Embedded subtitles should load successfully, allowing users to watch content with proper subtitles.

**Actual Result:**
Embedded subtitles fail to load, leaving users without the option to watch content that lacks external subtitles.

**Impact:**
This bug has a severe impact on user experience, as many users rely on embedded subtitles for content consumption. The inability to access these subtitles limits the usability of the Stremio app on Samsung TVs, especially when external subtitles are not available or are not synchronized properly.

**Additional Information:**
- **Stremio App Version:** latest
- **Samsung TV Model:** S95B
- **OS Version:** latest 

I kindly request your prompt attention to this matter, as it significantly affects the usability of the Stremio app on Samsung TVs. Your efforts to address and resolve this critical bug would be highly appreciated by the Stremio community.

Thank you for your time and dedication to improving the Stremio app.

Best regards,
Paz

**Comment by rodhfr** [comment]
As of today this bug is also present in the LG os version

**Comment by kriefsacha** [comment]
Hi, do they know about it ? All the embedded subtitles doesn't show on my samsung tv

**Comment by huminiucmihai** [comment]
Any updates on this? It is reaching a year since it was posted - it hurts a lot of anime for example which have embedded subtitles but absolutely no external ones

**Comment by kriefsacha** [comment]
@huminiucmihai when i posted on their blog 4 months ago they told me they knew about it and were working on it..

**Comment by jaruba** [comment]
it is out of our hands, the samsung tv app reviews have been stuck for many many months:
https://forum.developer.samsung.com/t/the-length-of-tizen-app-approval-process/

it's probably related to the samsung union strike:
https://www.reuters.com/technology/samsung-electronics-main-south-korea-union-strike-over-pay-thursday-2024-08-13/

**Comment by huminiucmihai** [comment]
So there is a fix, it is just being held back by samsung's management?

**Comment by TRtomasz** [comment]
New app version has been released, this should be fixed now

**Comment by nelsonnetto** [comment]
Issue is still present in the latest version of Stremio on Samsung TV

**Comment by jaruba** [comment]
@nelsonnetto i do not believe that is the case? most recent version should support all embedded subtitles except: SSA/ASS subtitles (mostly used for anime, Samsung TV 2019 supports them but after that Samsung stopped support for such embedded subtitles, we cannot fix that), bitmap subtitles (found in old DVD releases only, no Samsung TV ever supported them, we cannot fix that), all other embedded subtitles should work

**Comment by abrxu** [comment]
same thing here, it's not solved. i have a samsung cu7700 50' and it doesnt work with embeeded subtitles, just addon subtitles. (we have already updated the app and also reinstalled it, it still not working!)

**Comment by MIKOLAJW197** [comment]
Issue still is there - app version Theater v1.7.1 (Platform Tizen 5.5) on Samsung TV

**Comment by Pinhastest** [comment]
Problem remain unsolved

**Comment by rubenvc** [comment]
Theater v1.8.3 embedded subtitles not loading

**Comment by weberxw** [comment]
Guys, I was facing the same issue with the following setup:
torrentio + RD
debridio + RD

I don't know why but after reinstalling **torrentio without RD** and leaving **RD only on debridio** now the subtitles doesn't show anymore as UNKNOWN on my Samsung TV with Tyzen.... Maybe that can help anyone else.
