### ISSUE TITLE
[Linux/Wayland] When idle inhibit dbus events are being received, player hangs on pause

### ISSUE THREAD

**Issue by ItsDrike** [Stremio/stremio-bugs#695]
**Describe the bug**
This is a really weird one, and I'm not entirely sure what's going on here, however here's what I'm observing.

For a while now, I've been using `swayidle`, which is a daemon for wayland which detects idling, and performs some action after some amount of inactivity (like say start a screen locker after 5 minutes). Recently, I've moved from `swayidle` to [`hypridle`](https://github.com/hyprwm/hypridle), which is doing pretty much the same thing, but it also adds support for handling dbus events for idle inihibition.

While `hypridle` is running, whenever a video starts, it properly receives the idle inhibit cookie via dbus from stremio. However once I pause a video, stremio completely freezes and this appears in logs: 
```
[vo/opengl-cb] mpv_render_context_render() not being called or stuck.
```
Immediately once I kill `hypridle`, stremio starts working again.

**To Reproduce**
1. Install `hypridle` on `Hyprland`
2. Run `hypridle`
3. Start stremio and start watching something
4. Observe `hypridle` getting the idle inhibit cookie properly in it's logs, and everything running smoothly
5. Attempt to pause the video
6. Observe `[vo/opengl-cb] mpv_render_context_render() not being called or stuck.` in stremio logs, freezing it completely
7. Kill `hypridle`
8. Observe stremio unfreezing and pausing the video, with further resume & pausing working properly now, until `hypridle` is started agian.

**Expected behavior**
I don't have enough knowledge into how dbus events work here, so I'm not sure what's causing this exactly, it is entirely possible that this is an issue on `hypridle`'s side, rather than on stremio's side, although even if that was the case, and `hypridle` was improperly handling these dbus events, I don't think stremio should just hang like this because of it.

**Screenshots**

https://github.com/Stremio/stremio-bugs/assets/20902250/bd96d2b5-ff1a-47dd-9038-e15247c6c01e

**Desktop (please complete the following information):**
 - OS: Arch Linux, kernel 6.7.5-arch1-1
 - Stremio installed from AUR (Arch User Repository) (`stremio` package, version 4.4.165-1)
 - In-application shown stremio Version (in settings): 4.4.162
 - In-application shown WebUI Version (in settings): 4.4.171
- In-application shown Server Version (in settings): 4.19.0
- Wayland compositor: Hyprland v0.35.0
- Hypridle built from commit [`88a7220`](https://github.com/hyprwm/hypridle/commit/56f334cbe8679d6600d125d3dd1e3abbefcd34e8)

**Comment by TRtomasz** [comment]
some time ago this was introduced https://github.com/Stremio/stremio-shell/pull/173 could be related

**Comment by ItsDrike** [comment]
Okay, to make this probably a lot simpler, removing the need to look into how `hypridle` software works, I was able to create a minimal version of the dbus event reader in C++ which also causes the issue in stremio:

```cpp
#include <iostream>
#include <sdbus-c++/sdbus-c++.h>

void HandleDbusScreensaver(sdbus::MethodCall call, bool inhibit) {
  std::cout << "Trig" << std::endl;
}

void registerDbus() {
  std::cout << "Registering DBUS events" << std::endl;

  auto conn = sdbus::createSessionBusConnection("org.freedesktop.ScreenSaver");
  auto obj = sdbus::createObject(*conn, "/org/freedesktop/ScreenSaver");

  obj->registerMethod(
      "org.freedesktop.ScreenSaver", "Inhibit", "ss", "u",
      [&](sdbus::MethodCall c) { HandleDbusScreensaver(c, true); });
  obj->registerMethod(
      "org.freedesktop.ScreenSaver", "UnInhibit", "u", "",
      [&](sdbus::MethodCall c) { HandleDbusScreensaver(c, false); });
  obj->finishRegistration();

  std::cout << "DBUS events registered" << std::endl;

  conn->enterEventLoop();
}

int main(int argc, char *argv[]) {
  registerDbus();
  std::cout << "Event loop ended" << std::endl;
  return 0;
}
```

(compiled with: `g++ dbus_test.cpp -o dbus_test -lsdbus-c++ `, requires `sdbus-c++`)

**Comment by ItsDrike** [comment]
Okay, i think I found out what's going on, with this code, the issue doesn't occur:

```cpp
#include <cstdint>
#include <iostream>
#include <sdbus-c++/sdbus-c++.h>

void HandleInhibit(sdbus::MethodCall call) {
  static int cookieId = 1337;
  std::string app = "?";
  std::string reason = "?";

  call >> app;
  call >> reason;

  std::cout << "Got Inhibit from: " << app << ", reason: " << reason
            << std::endl;
  std::cout << "Assigning cookie id: " << cookieId << std::endl;

  auto reply = call.createReply();
  reply << uint32_t(cookieId++);
  reply.send();
}

void HandleUnInhibit(sdbus::MethodCall call) {
  uint32_t cookie = 0;
  call >> cookie;
  std::cout << "Got Uninhibit, cookie: " << cookie << std::endl;
  auto reply = call.createReply();
  reply.send();
}

void registerDbus() {
  std::cout << "Registering DBUS events" << std::endl;

  auto conn = sdbus::createSessionBusConnection("org.freedesktop.ScreenSaver");
  auto obj = sdbus::createObject(*conn, "/org/freedesktop/ScreenSaver");

  obj->registerMethod("org.freedesktop.ScreenSaver", "Inhibit", "ss", "u",
                      [&](sdbus::MethodCall c) { HandleInhibit(c); });
  obj->registerMethod("org.freedesktop.ScreenSaver", "UnInhibit", "u", "",
                      [&](sdbus::MethodCall c) { HandleUnInhibit(c); });
  obj->finishRegistration();

  std::cout << "DBUS events registered" << std::endl;

  conn->enterEventLoop();
}

int main(int argc, char *argv[]) {
  registerDbus();
  std::cout << "Event loop ended" << std::endl;
  return 0;
}
```

which leads me to believe stremio expects there to be a response if the event is read. Hypridle does send a response on inhibit, but it doesn't send one on uninhibit, which is what stremio wasn't able to handle. I will report this back to hypridle, however I still think it's unreasonable for stremio to just completely hang if there is an application reading these events improperly, so I'd still count this as a stremio bug too.

**Comment by TRtomasz** [comment]
i guess this could be closed since underlying issue in the software has been fixed?

**Comment by ItsDrike** [comment]
Yes and no, as I said, I still don't think the stremio behavior here is great, an error in another application shouldn't be able to completely freeze stremio. I still believe the better solution would instead be to run this logic in a separate thread and send an error log after some time if the response wasn't received.

That said, yeah, I no longer face this issue, hypridle does now send an empty response back, so I don't consider it a huge priority and if you don't wish to implement it, that's fine, just wanted to mention this.
