### ISSUE TITLE
Can’t disable subtitles permanently 

### ISSUE THREAD

**Issue by Johnboy90** [Stremio/stremio-bugs#762]
**Describe the bug**
Cannot turn off subtitles on the Samsung TV app. Even though default subtitle language is set to none they still automatically turn on every show. Also if you turn them off inside the episode and exit the app, when you return to the episode they are on again.

**To Reproduce**
1. Turn off subtitles in setting
2. Start a show

**Expected behavior**
Subtitles should be off by default when starting an episode. 

**Screenshots**
N/A

**TV (please complete the following information):**
 - Device: UE55TU7100KXXU
 - OS: Samsung
 
**Additional context**
From what I’ve read online it seems that this is a problem that applies to everyone, and has been since release as I found a similar post mentioning this from 3 months ago. The app is perfect otherwise, thank you!

**Comment by babolimp** [comment]
just wanted to second this issue. pretty annoying having to turn off subtitles manually with each and every video i watch.

TV used: samsung s90c

**Comment by TRtomasz** [comment]
This will be fixed in the next release

**Comment by adrianrza** [comment]
It's still not fixed

**Comment by TRtomasz** [comment]
New app version has been released, this should be fixed now

**Comment by ysnblk** [comment]
Not fixed on, its driving me nuts on my samsung CU7100

**Comment by andi-klein** [comment]
Problem unfortunately still exists in version 1.5.0 of the Samsung app (in-app About screen says Theater v1.7.2)

**Comment by wadewilson1990** [comment]
Problem also exists on LG version of the app

**Comment by vince1393** [comment]
This issue still exists for me too. It's really annoying. Any chance we can get a fix? I'm running on a Samsung S90D

**Comment by helenkellerseesall** [comment]
still not fixed and that’s absolutely crazy.

**Comment by FatestSquirrel** [comment]
So has it been fixed, but we just aren't seeing the fix? Or its still annoying people with every single video  we play a year and a half later? 😡

**Comment by alexbrazier** [comment]
Looks like it might have just been fixed 🤔 https://github.com/Stremio/stremio-video/pull/126

Hopefully an update to the Samsung store is on it's way soon 🤞

**Comment by ojordan099** [comment]
Still not working, issue has been here for ages, any update? I still have to manually turn them off each time I start a new episode or movie.
