### ISSUE TITLE
Subtitles doesn't work well in Samsung TV

### ISSUE THREAD

**Issue by Wainberg90** [Stremio/stremio-bugs#802]
**Describe the bug**
When I want to use subtitles from an external source it always gives an error, this has happened since the last update on Samsung TV. On the other devices (Computer, Cell phone) they work correctly, so I know that the problem is not with the addon itself.

Also, when I want to use Stremio's own, they are always poorly synchronized and the delay control often does not work correctly, but every 2 seconds it moves again and it is impossible to watch the movie, arranging the subtitles every 2 seconds.

**To Reproduce**
1 - I choose a movie
2 - I go to subtitles
3 - I choose the language
4 - I choose the community addon subtitle option
5 - Error appears: "failed to load external subtitles"

**Expected behavior**
What I hope is that the subtitles from external addons load correctly and that the delay control works once the times are set.

**TV (please complete the following information):**
 - Device: Samsung QN55Q60AAG
 - OS: Tizen (Samsung)

**Comment by TRtomasz** [comment]
What is your os version? I'v checked and i dont have any update available

**Comment by Wainberg90** [comment]
Hello, i have Tizen 2210

The problema si with the last update of stremio, not Tizen one.

Obtener Outlook para Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by DyingRocket55** [comment]
> **Describe the bug** When I want to use subtitles from an external source it always gives an error, this has happened since the last update on Samsung TV. On the other devices (Computer, Cell phone) they work correctly, so I know that the problem is not with the addon itself.
> 
> Also, when I want to use Stremio's own, they are always poorly synchronized and the delay control often does not work correctly, but every 2 seconds it moves again and it is impossible to watch the movie, arranging the subtitles every 2 seconds.
> 
> **To Reproduce** Steps to reproduce the behavior: 1 - I choose a movie 2 - I go to subtitles 3 - I choose the language 4 - I choose the community addon subtitle option 5 - Error appears: "failed to load external subtitles"
> 
> **Expected behavior** What I hope is that the subtitles from external addons load correctly and that the delay control works once the times are set.
> 
> **TV (please complete the following information):**
> 
> * Device: Samsung QN55Q60AAG
> * OS: Tizen (Samsung)

same issue.
device: Samsung QN77S90C

**Comment by jmbeltran07** [comment]
I have the same issue, the subtitles are not loading correctly on my Samsung tizen tv, specially when watching anime where the subtitles intend to appear on different places of the screen, I get a bunch of numbers and commands on screen instead of the actual formatted subtitles

**Comment by mosherimok** [comment]
It does the same error in my Samsung TV. Android app works great but Samsung app can't load external subtitles. Model QN90B

**Comment by geo-wurth** [comment]
Same issue here

**Comment by TRtomasz** [comment]
New app version has been released, this should be fixed now

**Comment by yassine-mdn** [comment]
Hey @TRtomasz 

This problem still persists even after the update being out for more than a month

**Comment by MafraLP** [comment]
Hi guys, any solution? 

Still having this issue
