### ISSUE TITLE
LG WebOS picks wrong Default Audio.

### ISSUE THREAD

**Issue by Ozoonn** [Stremio/stremio-bugs#917]
**Describe the bug**
When you start a movie/show it plays with a different Audio language than what you set as default, for me it's always in Russian when I have English set to Default Audio. 

**To Reproduce**
1. Go to 'Settings->Playback->Audio->Default Language->English'
2. Click on, Any movie that has multiple audio languages.
3. See error. 

**Expected behavior**
Audio to play on English. 

**TV (please complete the following information):**
 - LG: OLED 77 C3 
 - OS: WebOS
 - Version: 8.3.1-3607

**Additional context**
It also shows "RU", "EN" as audio language instead of "Russian", "English" as it does on Android TV. 

Subtitles are never showing by default, it shows as English but the first subtitle never work so you have to pick the subtitle that's underneath the first one.

I also have another LG Nanocell TV and it's the same thing there.

**Comment by TRtomasz** [comment]
this will be fixed in the next release

**Comment by Amuzements** [comment]
I'm running into this issue right now, where there are IT and EN Audio tracks and it's defaulting to the Italian ones even though my default language is English and I have none on secondary language. Wonder if this cropped up again?

**Comment by reginwillis** [comment]
I'm also experiencing this issue on latest WebOS

**Comment by JasonBSteele** [comment]
I am also experiencing this problem. Fresh install on 2024-12-24, Stremio version Theater v1.3.0, WebOS version 23.30.54

**Comment by JasonBSteele** [comment]
A couple of days ago the app got updated on my LG TV and it looks like this issue is now resolved :)

**Comment by kieranbrown** [comment]
I still have the same issue after updating to the latest WebOS Stremio version. My default audio language is set to English, but videos still default to Russian. Any ideas?

- LG: OLED 55 CX
- OS: WebOS
- Version: 5.5.0-1107

**Comment by JasonBSteele** [comment]
Yeah, it still seems to be a problem for me. It is better, but some reason Espanol is being chosen over English.

**Comment by TRtomasz** [comment]
any specific stream @kieranbrown @JasonBSteele ?

**Comment by JasonBSteele** [comment]
> any specific stream [@kieranbrown](https://github.com/kieranbrown) [@JasonBSteele](https://github.com/JasonBSteele) ?

Real Debrid

**Comment by kieranbrown** [comment]
Also using Real Debrid, how is best to share a stream?

The last stream I noticed this happen on was [Dexter Original Sin (S01E06)](https://www.strem.io/s/series/dexter-original-sin-32252772) using Torrentio / Real Debrid

Torrnt name is `Декстер: Первородный грех / Dexter: Original Sin / Сезон: 1 / Серии: 1-6 из 10 [2024 HEVC HDR10 HDR10+ Dolby Vision WEB-DL 2160p 4k] [Hybrid] MVO (HDrezka Studio LostFilm TVShows Red Head Sound 1WinStudio) + Original + Sub (Rus Eng)`

Honestly, though, it bugs me quite often. If you find any video with multiple audio tracks, I imagine you'll find at least one that doesn't select English properly. Let me know if there's a better way to share a stream.

**Comment by JasonBSteele** [comment]
> any specific stream [@kieranbrown](https://github.com/kieranbrown) [@JasonBSteele](https://github.com/JasonBSteele) ?

I found the stream link by opening though a browser on my laptop, pausing and clicking the ... menu on the bottom right of the screen.

https://torrentio.strem.fun/realdebrid/CADKA3SAWVFL6YF6JML55FTHYU6U366PKB7CPY57Z26SIDV4PBVQ/a34822092226322a6f0343d8e5f8c6e784613c3d/null/0/from.s03e01.spanish.latino.2160p.web-dl.ddp5.1.h.264-dem3nt3.mkv

this defaults to Spanish (Espanol) rather than the English.

**Comment by kieranbrown** [comment]
@TRtomasz did you manage to reproduce? Is it worth re-opening this issue or would you like me to create a new one?

**Comment by TRtomasz** [comment]
Cant reproduce it, in Tizen tv app, when you open audio tracks list do you see english as available option?

**Comment by JasonBSteele** [comment]
> Cant reproduce it, in Tizen tv app, when you open audio tracks list do you see english as available option?

Yes, English is listed as well. The language chosen is the first in the list - if it happens to be English you are lucky and it works - if not you have to go into the list and scroll down to find it.

**Comment by kieranbrown** [comment]
> > Cant reproduce it, in Tizen tv app, when you open audio tracks list do you see english as available option?
> 
> Yes, English is listed as well. The language chosen is the first in the list - if it happens to be English you are lucky and it works - if not you have to go into the list and scroll down to find it.

This is the behaviour I'm seeing too. The chosen language is just the first in the list.

**Comment by JasonBSteele** [comment]
> Cant reproduce it, in Tizen tv app, when you open audio tracks list do you see english as available option? We will test on lg soon

Can I help test any builds? I could deploy them to my TV using the dev mode. Feel free to DM me if that would be of any help.

**Comment by Diadrius** [comment]
Would like to confirm this issue still exists on the latest version available in the app store on LG C4 (OLED42C45LA).

Similar issue applies to the default subtitle language selection - though setting it to None, rebooting the app, setting it again and rebooting again seemed to work (only for the default subtitle language selection).

**Comment by mastermind85** [comment]
Same issue here.

**Comment by JasonBSteele** [comment]
> Cant reproduce it, in Tizen tv app, when you open audio tracks list do you see english as available option? We will test on lg soon

@TRtomasz , have you been able to reproduce this on an LG WebOS TV?

Should this issue be re-opened?

**Comment by salas164** [comment]
sept 2025 and this issues still has yet to be fixed 🙄

**Comment by WizardWell** [comment]
I have this issue myself right now. I will try to reinstall.

**Comment by Hutchyy9** [comment]
Still an issue

**Comment by WizardWell** [comment]
Same, reinstall did nothing

**Comment by WizardWell** [comment]
Thank you @TRtomasz for reopening! Message me if I can provide any further details on bug occurrence.

**Comment by tscan89** [comment]
Man, I really wish this could be fixed. This bug is very annoying.

**Comment by themyndzero** [comment]
it's 2026 and this is still an issue. I think it's a little more complicated even though. Regardless of what the "english" track is called, like it could be called some brand name thing that doesn't say English at all (nor do the few others above it that are also written in English), but the "English" track, in my experience, is ALWAYS the bottom one on the list. So maybe it's sorting and selecting them back to front, like in a reverse order and that's where this issue is coming from?

**Comment by jarrodrobins** [comment]
I am also having this exact issue. I also have my preferred language set to English and the vast majority of the time a language other than English plays. It's made worse by the fact that I'm also unable to change the language as there is no option available on the video. (#2158)

**Comment by Pete11** [comment]
It's the same for me, Russian is killing me. LG C2

**Comment by apollodaniel** [comment]
Got same problem on Samsung Tv Series 7, stremio theater 1.8.3, when I watch on mobile it shows languages as portuguese, and japanese, and select the default portuguese, but on tizen tv it shows jp and po and select jp as default even configured portuguese as default

**Comment by ajhutton** [comment]
Happening for me as well

**Comment by tscan89** [comment]
I wanted to take a stab at fixing this, but I don't think the LG WebOS version is open source? I was able to get setup with this repo relatively easily on my Windows PC (obviously the bug doesnt exist there). Anyone have information on the WebOS dev side of this? I primarily only use torrentio, so for now I've disabled all languages in the addon so I only get English streams, however not all addons will have this preference I'm sure.

**Comment by jaruba** [comment]
the only way to get access to the LG TV app code is by submitting the intern form from this page: https://www.stremio.com/community

**Comment by Ltraium** [comment]
this seems to of been going on for quite some time.
I have an LG C1 55in, using webOS 6, streamio version says Theaterv1.11.0
when I'm trying to watch my program on the TV it only gives me 2 audio tracks both are Russian but, on my pc, or any android device, I get a third audio track which is English.
I've checked all the settings a few times and know they are fine.
I have to go down to 480p before I find a stream with English audio. It's just about watchable but sucks.

**Comment by omrihefez** [comment]
Cross-linking — this looks like the same bug as #2564, which I filed today with a clean LG webOS C5 repro. I opened a fix in Stremio/stremio-web#1277 that retries `setAudioTrack` until the player acknowledges the selection (current code marks it done after one call, which silently fails on platforms where the underlying player has not finished initializing).

If you can re-test once the PR lands and report whether the bug is gone in your setup, that would help maintainers prioritize. Thanks for the original report.

**Comment by holmstromjesper** [comment]
Still an issue
